# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configuration.proto

require 'google/protobuf'

require 'soapbox_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "soapbox.ListConfigurationRequest" do
    optional :environment_id, :int32, 1
  end
  add_message "soapbox.ListConfigurationResponse" do
    repeated :configs, :message, 1, "soapbox.Configuration"
  end
  add_message "soapbox.GetLatestConfigurationRequest" do
    optional :environment_id, :int32, 1
  end
  add_message "soapbox.Configuration" do
    optional :environment_id, :int32, 1
    optional :version, :int32, 2
    optional :created_at, :message, 3, "google.protobuf.Timestamp"
    repeated :config_vars, :message, 4, "soapbox.ConfigVar"
  end
  add_message "soapbox.ConfigVar" do
    optional :name, :string, 1
    optional :value, :string, 2
  end
  add_message "soapbox.CreateConfigurationRequest" do
    optional :environment_id, :int32, 1
    repeated :config_vars, :message, 2, "soapbox.ConfigVar"
  end
  add_message "soapbox.DeleteConfigurationRequest" do
    optional :environment_id, :int32, 1
    optional :version, :int32, 2
  end
end

module Soapbox
  ListConfigurationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.ListConfigurationRequest").msgclass
  ListConfigurationResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.ListConfigurationResponse").msgclass
  GetLatestConfigurationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.GetLatestConfigurationRequest").msgclass
  Configuration = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.Configuration").msgclass
  ConfigVar = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.ConfigVar").msgclass
  CreateConfigurationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.CreateConfigurationRequest").msgclass
  DeleteConfigurationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.DeleteConfigurationRequest").msgclass
end
