# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deployment.proto

require 'google/protobuf'

require 'application_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "soapbox.StartDeploymentRequest" do
    optional :application, :message, 1, "soapbox.Application"
    optional :sha1OrTag, :string, 2
    map :env, :string, :string, 3
  end
  add_message "soapbox.StartDeploymentResponse" do
    optional :id, :int32, 1
  end
  add_message "soapbox.GetDeploymentStatusRequest" do
    optional :id, :int32, 1
  end
  add_message "soapbox.GetDeploymentStatusResponse" do
    optional :state, :string, 1
  end
end

module Soapbox
  StartDeploymentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.StartDeploymentRequest").msgclass
  StartDeploymentResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.StartDeploymentResponse").msgclass
  GetDeploymentStatusRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.GetDeploymentStatusRequest").msgclass
  GetDeploymentStatusResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.GetDeploymentStatusResponse").msgclass
end
