# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: deployment.proto for package 'soapbox'

require 'grpc'
require 'deployment_pb'

module Soapbox
  module Deployments
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'soapbox.Deployments'

      rpc :ListDeployments, Empty, ListDeploymentResponse
      rpc :GetDeployment, GetDeploymentRequest, Deployment
      rpc :StartDeployment, Deployment, StartDeploymentResponse
      rpc :GetDeploymentStatus, GetDeploymentStatusRequest, GetDeploymentStatusResponse
      rpc :TeardownDeployment, TeardownDeploymentRequest, Empty
    end

    Stub = Service.rpc_stub_class
  end
end
