# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deployment.proto

require 'google/protobuf'

require 'soapbox_pb'
require 'application_pb'
require 'environment_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "soapbox.ListDeploymentRequest" do
    optional :application_id, :int32, 1
  end
  add_message "soapbox.ListDeploymentResponse" do
    repeated :deployments, :message, 1, "soapbox.Deployment"
  end
  add_message "soapbox.GetDeploymentRequest" do
    optional :id, :int32, 1
  end
  add_message "soapbox.Deployment" do
    optional :id, :int32, 1
    optional :application, :message, 2, "soapbox.Application"
    optional :env, :message, 3, "soapbox.Environment"
    optional :committish, :string, 4
    optional :state, :enum, 5, "soapbox.DeploymentState"
    optional :created_at, :string, 6
  end
  add_message "soapbox.StartDeploymentResponse" do
    optional :id, :int32, 1
  end
  add_message "soapbox.GetDeploymentStatusRequest" do
    optional :id, :int32, 1
  end
  add_message "soapbox.GetDeploymentStatusResponse" do
    optional :state, :string, 1
  end
  add_message "soapbox.TeardownDeploymentRequest" do
    optional :id, :int32, 1
  end
  add_enum "soapbox.DeploymentState" do
    value :DEPLOYMENT_ROLLOUT_WAIT, 0
    value :DEPLOYMENT_EVALUATE_WAIT, 1
    value :DEPLOYMENT_ROLL_FORWARD, 2
    value :DEPLOYMENT_SUCCEEDED, 3
    value :DEPLOYMENT_FAILED, 4
  end
end

module Soapbox
  ListDeploymentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.ListDeploymentRequest").msgclass
  ListDeploymentResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.ListDeploymentResponse").msgclass
  GetDeploymentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.GetDeploymentRequest").msgclass
  Deployment = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.Deployment").msgclass
  StartDeploymentResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.StartDeploymentResponse").msgclass
  GetDeploymentStatusRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.GetDeploymentStatusRequest").msgclass
  GetDeploymentStatusResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.GetDeploymentStatusResponse").msgclass
  TeardownDeploymentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.TeardownDeploymentRequest").msgclass
  DeploymentState = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.DeploymentState").enummodule
end
