# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: environment.proto for package 'soapbox'

require 'grpc'
require 'environment_pb'

module Soapbox
  module Environments
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'soapbox.Environments'

      rpc :ListEnvironments, ListEnvironmentRequest, ListEnvironmentResponse
      rpc :GetEnvironment, GetEnvironmentRequest, Environment
      rpc :CreateEnvironment, Environment, Environment
      rpc :DestroyEnvironment, DestroyEnvironmentRequest, Empty
      rpc :CopyEnvironment, CopyEnvironmentRequest, Environment
    end

    Stub = Service.rpc_stub_class
  end
end
