# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: soapbox.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "soapbox.Empty" do
  end
end

module Soapbox
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.Empty").msgclass
end
