# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user.proto for package 'soapbox'

require 'grpc'
require 'user_pb'

module Soapbox
  module Users
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'soapbox.Users'

      rpc :CreateUser, CreateUserRequest, User
      rpc :GetUser, GetUserRequest, User
      rpc :LoginUser, LoginUserRequest, LoginUserResponse
      rpc :AssignGithubOmniauthTokenToUser, User, User
    end

    Stub = Service.rpc_stub_class
  end
end
