# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: version.proto

require 'google/protobuf'

require 'soapbox_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "soapbox.GetVersionResponse" do
    optional :version, :string, 1
    optional :git_commit, :string, 2
    optional :build_time, :string, 3
  end
end

module Soapbox
  GetVersionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("soapbox.GetVersionResponse").msgclass
end
