// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application.proto

package soapboxpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ApplicationType int32

const (
	ApplicationType_SERVER  ApplicationType = 0
	ApplicationType_CRONJOB ApplicationType = 1
)

var ApplicationType_name = map[int32]string{
	0: "SERVER",
	1: "CRONJOB",
}
var ApplicationType_value = map[string]int32{
	"SERVER":  0,
	"CRONJOB": 1,
}

func (x ApplicationType) String() string {
	return proto.EnumName(ApplicationType_name, int32(x))
}
func (ApplicationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type Application struct {
	Id                 int32           `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name               string          `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description        string          `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	ExternalDns        string          `protobuf:"bytes,4,opt,name=external_dns,json=externalDns" json:"external_dns,omitempty"`
	GithubRepoUrl      string          `protobuf:"bytes,5,opt,name=github_repo_url,json=githubRepoUrl" json:"github_repo_url,omitempty"`
	DockerfilePath     string          `protobuf:"bytes,6,opt,name=dockerfile_path,json=dockerfilePath" json:"dockerfile_path,omitempty"`
	EntrypointOverride string          `protobuf:"bytes,7,opt,name=entrypoint_override,json=entrypointOverride" json:"entrypoint_override,omitempty"`
	Type               ApplicationType `protobuf:"varint,8,opt,name=type,enum=soapbox.ApplicationType" json:"type,omitempty"`
	CreatedAt          string          `protobuf:"bytes,9,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Slug               string          `protobuf:"bytes,10,opt,name=slug" json:"slug,omitempty"`
	InternalDns        string          `protobuf:"bytes,11,opt,name=internal_dns,json=internalDns" json:"internal_dns,omitempty"`
}

func (m *Application) Reset()                    { *m = Application{} }
func (m *Application) String() string            { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()               {}
func (*Application) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Application) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Application) GetExternalDns() string {
	if m != nil {
		return m.ExternalDns
	}
	return ""
}

func (m *Application) GetGithubRepoUrl() string {
	if m != nil {
		return m.GithubRepoUrl
	}
	return ""
}

func (m *Application) GetDockerfilePath() string {
	if m != nil {
		return m.DockerfilePath
	}
	return ""
}

func (m *Application) GetEntrypointOverride() string {
	if m != nil {
		return m.EntrypointOverride
	}
	return ""
}

func (m *Application) GetType() ApplicationType {
	if m != nil {
		return m.Type
	}
	return ApplicationType_SERVER
}

func (m *Application) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Application) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Application) GetInternalDns() string {
	if m != nil {
		return m.InternalDns
	}
	return ""
}

type ListApplicationResponse struct {
	Applications []*Application `protobuf:"bytes,1,rep,name=applications" json:"applications,omitempty"`
}

func (m *ListApplicationResponse) Reset()                    { *m = ListApplicationResponse{} }
func (m *ListApplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*ListApplicationResponse) ProtoMessage()               {}
func (*ListApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ListApplicationResponse) GetApplications() []*Application {
	if m != nil {
		return m.Applications
	}
	return nil
}

type GetApplicationRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetApplicationRequest) Reset()                    { *m = GetApplicationRequest{} }
func (m *GetApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetApplicationRequest) ProtoMessage()               {}
func (*GetApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *GetApplicationRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Application)(nil), "soapbox.Application")
	proto.RegisterType((*ListApplicationResponse)(nil), "soapbox.ListApplicationResponse")
	proto.RegisterType((*GetApplicationRequest)(nil), "soapbox.GetApplicationRequest")
	proto.RegisterEnum("soapbox.ApplicationType", ApplicationType_name, ApplicationType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Applications service

type ApplicationsClient interface {
	ListApplications(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListApplicationResponse, error)
	CreateApplication(ctx context.Context, in *Application, opts ...grpc.CallOption) (*Application, error)
	GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*Application, error)
}

type applicationsClient struct {
	cc *grpc.ClientConn
}

func NewApplicationsClient(cc *grpc.ClientConn) ApplicationsClient {
	return &applicationsClient{cc}
}

func (c *applicationsClient) ListApplications(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListApplicationResponse, error) {
	out := new(ListApplicationResponse)
	err := grpc.Invoke(ctx, "/soapbox.Applications/ListApplications", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationsClient) CreateApplication(ctx context.Context, in *Application, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := grpc.Invoke(ctx, "/soapbox.Applications/CreateApplication", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationsClient) GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := grpc.Invoke(ctx, "/soapbox.Applications/GetApplication", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Applications service

type ApplicationsServer interface {
	ListApplications(context.Context, *Empty) (*ListApplicationResponse, error)
	CreateApplication(context.Context, *Application) (*Application, error)
	GetApplication(context.Context, *GetApplicationRequest) (*Application, error)
}

func RegisterApplicationsServer(s *grpc.Server, srv ApplicationsServer) {
	s.RegisterService(&_Applications_serviceDesc, srv)
}

func _Applications_ListApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).ListApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Applications/ListApplications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).ListApplications(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applications_CreateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Application)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).CreateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Applications/CreateApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).CreateApplication(ctx, req.(*Application))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applications_GetApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).GetApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Applications/GetApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).GetApplication(ctx, req.(*GetApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Applications_serviceDesc = grpc.ServiceDesc{
	ServiceName: "soapbox.Applications",
	HandlerType: (*ApplicationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListApplications",
			Handler:    _Applications_ListApplications_Handler,
		},
		{
			MethodName: "CreateApplication",
			Handler:    _Applications_CreateApplication_Handler,
		},
		{
			MethodName: "GetApplication",
			Handler:    _Applications_GetApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application.proto",
}

func init() { proto.RegisterFile("application.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xe3, 0x34, 0x4d, 0xc8, 0x38, 0x75, 0xd2, 0x01, 0xc4, 0x2a, 0x12, 0xc8, 0xf8, 0x40,
	0xa3, 0x0a, 0x15, 0x29, 0x5c, 0xb8, 0xa6, 0x6d, 0x00, 0x21, 0x44, 0x90, 0x0b, 0x1c, 0xb8, 0x58,
	0x4e, 0x3c, 0x34, 0x2b, 0xdc, 0xdd, 0x65, 0x77, 0x83, 0x9a, 0xcf, 0xcb, 0xd7, 0xe0, 0x50, 0x65,
	0x9d, 0x3f, 0x4e, 0x94, 0xdc, 0xc6, 0x6f, 0x9e, 0xc7, 0xf3, 0x7e, 0xeb, 0x85, 0xd3, 0x54, 0xa9,
	0x9c, 0x4f, 0x52, 0xcb, 0xa5, 0xb8, 0x50, 0x5a, 0x5a, 0x89, 0x0d, 0x23, 0x53, 0x35, 0x96, 0xf7,
	0xdd, 0x93, 0x65, 0x51, 0xe8, 0xd1, 0xff, 0x2a, 0xf8, 0x83, 0x8d, 0x1b, 0x03, 0xa8, 0xf2, 0x8c,
	0x79, 0xa1, 0xd7, 0x3b, 0x8e, 0xab, 0x3c, 0x43, 0x84, 0x9a, 0x48, 0xef, 0x88, 0x55, 0x43, 0xaf,
	0xd7, 0x8c, 0x5d, 0x8d, 0x21, 0xf8, 0x19, 0x99, 0x89, 0xe6, 0x6a, 0xf1, 0x0a, 0x3b, 0x72, 0xad,
	0xb2, 0x84, 0x2f, 0xa1, 0x45, 0xf7, 0x96, 0xb4, 0x48, 0xf3, 0x24, 0x13, 0x86, 0xd5, 0x0a, 0xcb,
	0x4a, 0xbb, 0x16, 0x06, 0x5f, 0x41, 0xfb, 0x96, 0xdb, 0xe9, 0x6c, 0x9c, 0x68, 0x52, 0x32, 0x99,
	0xe9, 0x9c, 0x1d, 0x3b, 0xd7, 0x49, 0x21, 0xc7, 0xa4, 0xe4, 0x77, 0x9d, 0xe3, 0x19, 0xb4, 0x33,
	0x39, 0xf9, 0x4d, 0xfa, 0x17, 0xcf, 0x29, 0x51, 0xa9, 0x9d, 0xb2, 0xba, 0xf3, 0x05, 0x1b, 0xf9,
	0x6b, 0x6a, 0xa7, 0xf8, 0x06, 0x1e, 0x93, 0xb0, 0x7a, 0xae, 0x24, 0x17, 0x36, 0x91, 0x7f, 0x49,
	0x6b, 0x9e, 0x11, 0x6b, 0x38, 0x33, 0x6e, 0x5a, 0xa3, 0x65, 0x07, 0x5f, 0x43, 0xcd, 0xce, 0x15,
	0xb1, 0x47, 0xa1, 0xd7, 0x0b, 0xfa, 0xec, 0x62, 0x05, 0xa6, 0x84, 0xe3, 0xdb, 0x5c, 0x51, 0xec,
	0x5c, 0xf8, 0x1c, 0x60, 0xa2, 0x29, 0xb5, 0x94, 0x25, 0xa9, 0x65, 0x4d, 0x37, 0xb5, 0xb9, 0x54,
	0x06, 0x76, 0xc1, 0xc9, 0xe4, 0xb3, 0x5b, 0x06, 0x05, 0xa7, 0x45, 0xbd, 0xa0, 0xc0, 0x45, 0x89,
	0x82, 0x5f, 0x50, 0x58, 0x69, 0xd7, 0xc2, 0x44, 0x37, 0xf0, 0xec, 0x33, 0x37, 0xb6, 0xf4, 0xc9,
	0x98, 0x8c, 0x92, 0xc2, 0x10, 0xbe, 0x83, 0x56, 0xe9, 0x18, 0x0d, 0xf3, 0xc2, 0xa3, 0x9e, 0xdf,
	0x7f, 0xb2, 0x6f, 0xcd, 0x78, 0xcb, 0x19, 0x9d, 0xc1, 0xd3, 0x0f, 0xb4, 0x3d, 0xf3, 0xcf, 0x8c,
	0x8c, 0xdd, 0x3d, 0xdc, 0xf3, 0x73, 0x68, 0xef, 0x84, 0x45, 0x80, 0xfa, 0xcd, 0x30, 0xfe, 0x31,
	0x8c, 0x3b, 0x15, 0xf4, 0xa1, 0x71, 0x15, 0x8f, 0xbe, 0x7c, 0x1a, 0x5d, 0x76, 0xbc, 0xfe, 0x3f,
	0x0f, 0x5a, 0x25, 0xb3, 0xc1, 0xf7, 0xd0, 0xd9, 0x59, 0xdd, 0x60, 0xb0, 0xde, 0x6e, 0x78, 0xa7,
	0xec, 0xbc, 0x1b, 0xae, 0x9f, 0x0f, 0xa4, 0x8c, 0x2a, 0x38, 0x80, 0xd3, 0x2b, 0x87, 0xb1, 0xfc,
	0x1b, 0xee, 0x8d, 0xd9, 0xdd, 0xab, 0x46, 0x15, 0xfc, 0x08, 0xc1, 0x76, 0x60, 0x7c, 0xb1, 0x76,
	0xee, 0x25, 0x71, 0x68, 0xd2, 0xa5, 0xff, 0xb3, 0xb9, 0x6c, 0xa8, 0xf1, 0xb8, 0xee, 0xae, 0xc8,
	0xdb, 0x87, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x9b, 0x7c, 0xcf, 0x4f, 0x03, 0x00, 0x00,
}
