// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deployment.proto

package soapboxpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ListDeploymentRequest struct {
}

func (m *ListDeploymentRequest) Reset()                    { *m = ListDeploymentRequest{} }
func (m *ListDeploymentRequest) String() string            { return proto.CompactTextString(m) }
func (*ListDeploymentRequest) ProtoMessage()               {}
func (*ListDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type ListDeploymentResponse struct {
	Deployments []*Deployment `protobuf:"bytes,1,rep,name=deployments" json:"deployments,omitempty"`
}

func (m *ListDeploymentResponse) Reset()                    { *m = ListDeploymentResponse{} }
func (m *ListDeploymentResponse) String() string            { return proto.CompactTextString(m) }
func (*ListDeploymentResponse) ProtoMessage()               {}
func (*ListDeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ListDeploymentResponse) GetDeployments() []*Deployment {
	if m != nil {
		return m.Deployments
	}
	return nil
}

type GetDeploymentRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetDeploymentRequest) Reset()                    { *m = GetDeploymentRequest{} }
func (m *GetDeploymentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDeploymentRequest) ProtoMessage()               {}
func (*GetDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *GetDeploymentRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Deployment struct {
	Id        int32        `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	State     string       `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Env       *Environment `protobuf:"bytes,3,opt,name=env" json:"env,omitempty"`
	CreatedAt string       `protobuf:"bytes,4,opt,name=createdAt" json:"createdAt,omitempty"`
}

func (m *Deployment) Reset()                    { *m = Deployment{} }
func (m *Deployment) String() string            { return proto.CompactTextString(m) }
func (*Deployment) ProtoMessage()               {}
func (*Deployment) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Deployment) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Deployment) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Deployment) GetEnv() *Environment {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Deployment) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type StartDeploymentRequest struct {
	Application *Application `protobuf:"bytes,1,opt,name=application" json:"application,omitempty"`
	Sha1OrTag   string       `protobuf:"bytes,2,opt,name=sha1OrTag" json:"sha1OrTag,omitempty"`
	Env         *Environment `protobuf:"bytes,3,opt,name=env" json:"env,omitempty"`
}

func (m *StartDeploymentRequest) Reset()                    { *m = StartDeploymentRequest{} }
func (m *StartDeploymentRequest) String() string            { return proto.CompactTextString(m) }
func (*StartDeploymentRequest) ProtoMessage()               {}
func (*StartDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *StartDeploymentRequest) GetApplication() *Application {
	if m != nil {
		return m.Application
	}
	return nil
}

func (m *StartDeploymentRequest) GetSha1OrTag() string {
	if m != nil {
		return m.Sha1OrTag
	}
	return ""
}

func (m *StartDeploymentRequest) GetEnv() *Environment {
	if m != nil {
		return m.Env
	}
	return nil
}

type StartDeploymentResponse struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *StartDeploymentResponse) Reset()                    { *m = StartDeploymentResponse{} }
func (m *StartDeploymentResponse) String() string            { return proto.CompactTextString(m) }
func (*StartDeploymentResponse) ProtoMessage()               {}
func (*StartDeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *StartDeploymentResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetDeploymentStatusRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetDeploymentStatusRequest) Reset()                    { *m = GetDeploymentStatusRequest{} }
func (m *GetDeploymentStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDeploymentStatusRequest) ProtoMessage()               {}
func (*GetDeploymentStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *GetDeploymentStatusRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetDeploymentStatusResponse struct {
	State string `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
}

func (m *GetDeploymentStatusResponse) Reset()                    { *m = GetDeploymentStatusResponse{} }
func (m *GetDeploymentStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDeploymentStatusResponse) ProtoMessage()               {}
func (*GetDeploymentStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *GetDeploymentStatusResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type TeardownDeploymentRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *TeardownDeploymentRequest) Reset()                    { *m = TeardownDeploymentRequest{} }
func (m *TeardownDeploymentRequest) String() string            { return proto.CompactTextString(m) }
func (*TeardownDeploymentRequest) ProtoMessage()               {}
func (*TeardownDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *TeardownDeploymentRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type TeardownDeploymentResponse struct {
}

func (m *TeardownDeploymentResponse) Reset()                    { *m = TeardownDeploymentResponse{} }
func (m *TeardownDeploymentResponse) String() string            { return proto.CompactTextString(m) }
func (*TeardownDeploymentResponse) ProtoMessage()               {}
func (*TeardownDeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func init() {
	proto.RegisterType((*ListDeploymentRequest)(nil), "soapbox.ListDeploymentRequest")
	proto.RegisterType((*ListDeploymentResponse)(nil), "soapbox.ListDeploymentResponse")
	proto.RegisterType((*GetDeploymentRequest)(nil), "soapbox.GetDeploymentRequest")
	proto.RegisterType((*Deployment)(nil), "soapbox.Deployment")
	proto.RegisterType((*StartDeploymentRequest)(nil), "soapbox.StartDeploymentRequest")
	proto.RegisterType((*StartDeploymentResponse)(nil), "soapbox.StartDeploymentResponse")
	proto.RegisterType((*GetDeploymentStatusRequest)(nil), "soapbox.GetDeploymentStatusRequest")
	proto.RegisterType((*GetDeploymentStatusResponse)(nil), "soapbox.GetDeploymentStatusResponse")
	proto.RegisterType((*TeardownDeploymentRequest)(nil), "soapbox.TeardownDeploymentRequest")
	proto.RegisterType((*TeardownDeploymentResponse)(nil), "soapbox.TeardownDeploymentResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Deployments service

type DeploymentsClient interface {
	ListDeployments(ctx context.Context, in *ListDeploymentRequest, opts ...grpc.CallOption) (*ListDeploymentResponse, error)
	GetDeployment(ctx context.Context, in *GetDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error)
	StartDeployment(ctx context.Context, in *StartDeploymentRequest, opts ...grpc.CallOption) (*StartDeploymentResponse, error)
	GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error)
	TeardownDeployment(ctx context.Context, in *TeardownDeploymentRequest, opts ...grpc.CallOption) (*TeardownDeploymentResponse, error)
}

type deploymentsClient struct {
	cc *grpc.ClientConn
}

func NewDeploymentsClient(cc *grpc.ClientConn) DeploymentsClient {
	return &deploymentsClient{cc}
}

func (c *deploymentsClient) ListDeployments(ctx context.Context, in *ListDeploymentRequest, opts ...grpc.CallOption) (*ListDeploymentResponse, error) {
	out := new(ListDeploymentResponse)
	err := grpc.Invoke(ctx, "/soapbox.Deployments/ListDeployments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsClient) GetDeployment(ctx context.Context, in *GetDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error) {
	out := new(Deployment)
	err := grpc.Invoke(ctx, "/soapbox.Deployments/GetDeployment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsClient) StartDeployment(ctx context.Context, in *StartDeploymentRequest, opts ...grpc.CallOption) (*StartDeploymentResponse, error) {
	out := new(StartDeploymentResponse)
	err := grpc.Invoke(ctx, "/soapbox.Deployments/StartDeployment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsClient) GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error) {
	out := new(GetDeploymentStatusResponse)
	err := grpc.Invoke(ctx, "/soapbox.Deployments/GetDeploymentStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsClient) TeardownDeployment(ctx context.Context, in *TeardownDeploymentRequest, opts ...grpc.CallOption) (*TeardownDeploymentResponse, error) {
	out := new(TeardownDeploymentResponse)
	err := grpc.Invoke(ctx, "/soapbox.Deployments/TeardownDeployment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Deployments service

type DeploymentsServer interface {
	ListDeployments(context.Context, *ListDeploymentRequest) (*ListDeploymentResponse, error)
	GetDeployment(context.Context, *GetDeploymentRequest) (*Deployment, error)
	StartDeployment(context.Context, *StartDeploymentRequest) (*StartDeploymentResponse, error)
	GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error)
	TeardownDeployment(context.Context, *TeardownDeploymentRequest) (*TeardownDeploymentResponse, error)
}

func RegisterDeploymentsServer(s *grpc.Server, srv DeploymentsServer) {
	s.RegisterService(&_Deployments_serviceDesc, srv)
}

func _Deployments_ListDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).ListDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Deployments/ListDeployments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).ListDeployments(ctx, req.(*ListDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deployments_GetDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).GetDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Deployments/GetDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).GetDeployment(ctx, req.(*GetDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deployments_StartDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).StartDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Deployments/StartDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).StartDeployment(ctx, req.(*StartDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deployments_GetDeploymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).GetDeploymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Deployments/GetDeploymentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).GetDeploymentStatus(ctx, req.(*GetDeploymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deployments_TeardownDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeardownDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).TeardownDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Deployments/TeardownDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).TeardownDeployment(ctx, req.(*TeardownDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Deployments_serviceDesc = grpc.ServiceDesc{
	ServiceName: "soapbox.Deployments",
	HandlerType: (*DeploymentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDeployments",
			Handler:    _Deployments_ListDeployments_Handler,
		},
		{
			MethodName: "GetDeployment",
			Handler:    _Deployments_GetDeployment_Handler,
		},
		{
			MethodName: "StartDeployment",
			Handler:    _Deployments_StartDeployment_Handler,
		},
		{
			MethodName: "GetDeploymentStatus",
			Handler:    _Deployments_GetDeploymentStatus_Handler,
		},
		{
			MethodName: "TeardownDeployment",
			Handler:    _Deployments_TeardownDeployment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deployment.proto",
}

func init() { proto.RegisterFile("deployment.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x51, 0xcf, 0xd2, 0x30,
	0x14, 0xfd, 0xc6, 0xfc, 0x34, 0xdc, 0x45, 0x3f, 0x29, 0x08, 0xb3, 0xa2, 0x2e, 0xc5, 0x90, 0x19,
	0x0d, 0x89, 0x10, 0x7d, 0xc7, 0x48, 0x7c, 0x31, 0x21, 0x19, 0xc4, 0x07, 0x5f, 0x4c, 0xc7, 0x1a,
	0x5d, 0x82, 0xeb, 0x5c, 0x0b, 0xe2, 0x1f, 0xf1, 0x2f, 0xf9, 0xb7, 0x0c, 0x6c, 0xb6, 0xdb, 0xe8,
	0xd0, 0xc7, 0xdd, 0x7b, 0xee, 0x3d, 0xa7, 0xe7, 0xdc, 0x0c, 0xee, 0x47, 0x2c, 0xdd, 0xf2, 0x9f,
	0xdf, 0x58, 0x22, 0x27, 0x69, 0xc6, 0x25, 0x47, 0x77, 0x04, 0xa7, 0x69, 0xc8, 0x0f, 0xb8, 0x43,
	0xd3, 0x74, 0x1b, 0x6f, 0xa8, 0x8c, 0x79, 0x92, 0xf7, 0x70, 0x87, 0x25, 0xfb, 0x38, 0xe3, 0x89,
	0x86, 0x93, 0x01, 0x3c, 0xf8, 0x10, 0x0b, 0xf9, 0x4e, 0xad, 0x09, 0xd8, 0xf7, 0x1d, 0x13, 0x92,
	0x2c, 0xa1, 0x5f, 0x6f, 0x88, 0x94, 0x27, 0x82, 0xa1, 0xd7, 0xe0, 0x68, 0x56, 0xe1, 0x5a, 0x9e,
	0xed, 0x3b, 0xd3, 0xee, 0xa4, 0xe0, 0x9d, 0x94, 0x26, 0xca, 0x38, 0x32, 0x86, 0xde, 0x7b, 0x76,
	0x4e, 0x84, 0xee, 0x41, 0x2b, 0x8e, 0x5c, 0xcb, 0xb3, 0xfc, 0xeb, 0xa0, 0x15, 0x47, 0xe4, 0x00,
	0xa0, 0x41, 0xf5, 0x2e, 0xea, 0xc1, 0xb5, 0x90, 0x54, 0x32, 0xb7, 0xe5, 0x59, 0x7e, 0x3b, 0xc8,
	0x3f, 0xd0, 0x18, 0x6c, 0x96, 0xec, 0x5d, 0xdb, 0xb3, 0x7c, 0x67, 0xda, 0x53, 0x52, 0x16, 0xfa,
	0xb9, 0xc1, 0x11, 0x80, 0x86, 0xd0, 0xde, 0x64, 0x8c, 0x4a, 0x16, 0xcd, 0xa5, 0x7b, 0xeb, 0xb4,
	0x41, 0x17, 0xc8, 0x2f, 0x0b, 0xfa, 0x2b, 0x49, 0x33, 0x83, 0xc8, 0x37, 0xe0, 0x94, 0xec, 0x3c,
	0xe9, 0x29, 0x13, 0xcd, 0x75, 0x2f, 0x28, 0x03, 0x8f, 0x84, 0xe2, 0x2b, 0x7d, 0xb5, 0xcc, 0xd6,
	0xf4, 0x4b, 0x21, 0x59, 0x17, 0xfe, 0x57, 0x36, 0x79, 0x0e, 0x83, 0x33, 0x5d, 0x45, 0x18, 0x75,
	0xf7, 0x5e, 0x02, 0xae, 0xb8, 0xbc, 0x92, 0x54, 0xee, 0x44, 0x93, 0xd7, 0x33, 0x78, 0x64, 0x44,
	0x17, 0xcb, 0x95, 0xd9, 0x56, 0xc9, 0x6c, 0xf2, 0x02, 0x1e, 0xae, 0x19, 0xcd, 0x22, 0xfe, 0x23,
	0xf9, 0x77, 0x9a, 0x43, 0xc0, 0x26, 0x70, 0x4e, 0x30, 0xfd, 0x6d, 0x83, 0xa3, 0xcb, 0x02, 0xad,
	0xe1, 0xa6, 0x7a, 0x74, 0x02, 0x3d, 0x51, 0xb6, 0x18, 0xef, 0x14, 0x3f, 0x6d, 0xec, 0xe7, 0x1c,
	0xe4, 0x0a, 0x2d, 0xe0, 0x6e, 0xe5, 0x95, 0xe8, 0xb1, 0x9a, 0x31, 0x5d, 0x24, 0x36, 0xdd, 0x32,
	0xb9, 0x42, 0x1f, 0xe1, 0xa6, 0x96, 0x02, 0xd2, 0xe4, 0xe6, 0xbb, 0xc1, 0x5e, 0x33, 0x40, 0xc9,
	0x0b, 0xa1, 0x6b, 0x08, 0x01, 0x8d, 0xcc, 0x22, 0x2b, 0x81, 0xe2, 0x67, 0x97, 0x41, 0x8a, 0xe3,
	0x33, 0xa0, 0xf3, 0x18, 0x10, 0x51, 0xd3, 0x8d, 0x81, 0xe2, 0xd1, 0x45, 0xcc, 0x5f, 0x82, 0xb7,
	0xce, 0xa7, 0x76, 0x81, 0x4b, 0xc3, 0xf0, 0xf6, 0xe9, 0xdf, 0x32, 0xfb, 0x13, 0x00, 0x00, 0xff,
	0xff, 0xc1, 0x16, 0xc1, 0x52, 0x9e, 0x04, 0x00, 0x00,
}
