// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deployment.proto

package soapboxpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ListDeploymentRequest struct {
	ApplicationId int32 `protobuf:"varint,1,opt,name=application_id,json=applicationId" json:"application_id,omitempty"`
}

func (m *ListDeploymentRequest) Reset()                    { *m = ListDeploymentRequest{} }
func (m *ListDeploymentRequest) String() string            { return proto.CompactTextString(m) }
func (*ListDeploymentRequest) ProtoMessage()               {}
func (*ListDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *ListDeploymentRequest) GetApplicationId() int32 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

type ListDeploymentResponse struct {
	Deployments []*Deployment `protobuf:"bytes,1,rep,name=deployments" json:"deployments,omitempty"`
}

func (m *ListDeploymentResponse) Reset()                    { *m = ListDeploymentResponse{} }
func (m *ListDeploymentResponse) String() string            { return proto.CompactTextString(m) }
func (*ListDeploymentResponse) ProtoMessage()               {}
func (*ListDeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *ListDeploymentResponse) GetDeployments() []*Deployment {
	if m != nil {
		return m.Deployments
	}
	return nil
}

type GetDeploymentRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetDeploymentRequest) Reset()                    { *m = GetDeploymentRequest{} }
func (m *GetDeploymentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDeploymentRequest) ProtoMessage()               {}
func (*GetDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *GetDeploymentRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Deployment struct {
	Id          int32        `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Application *Application `protobuf:"bytes,2,opt,name=application" json:"application,omitempty"`
	Env         *Environment `protobuf:"bytes,3,opt,name=env" json:"env,omitempty"`
	Committish  string       `protobuf:"bytes,4,opt,name=committish" json:"committish,omitempty"`
	State       string       `protobuf:"bytes,5,opt,name=state" json:"state,omitempty"`
	CreatedAt   string       `protobuf:"bytes,6,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *Deployment) Reset()                    { *m = Deployment{} }
func (m *Deployment) String() string            { return proto.CompactTextString(m) }
func (*Deployment) ProtoMessage()               {}
func (*Deployment) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *Deployment) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Deployment) GetApplication() *Application {
	if m != nil {
		return m.Application
	}
	return nil
}

func (m *Deployment) GetEnv() *Environment {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Deployment) GetCommittish() string {
	if m != nil {
		return m.Committish
	}
	return ""
}

func (m *Deployment) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Deployment) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type StartDeploymentResponse struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *StartDeploymentResponse) Reset()                    { *m = StartDeploymentResponse{} }
func (m *StartDeploymentResponse) String() string            { return proto.CompactTextString(m) }
func (*StartDeploymentResponse) ProtoMessage()               {}
func (*StartDeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *StartDeploymentResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetDeploymentStatusRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetDeploymentStatusRequest) Reset()                    { *m = GetDeploymentStatusRequest{} }
func (m *GetDeploymentStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDeploymentStatusRequest) ProtoMessage()               {}
func (*GetDeploymentStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *GetDeploymentStatusRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetDeploymentStatusResponse struct {
	State string `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
}

func (m *GetDeploymentStatusResponse) Reset()                    { *m = GetDeploymentStatusResponse{} }
func (m *GetDeploymentStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDeploymentStatusResponse) ProtoMessage()               {}
func (*GetDeploymentStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *GetDeploymentStatusResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type TeardownDeploymentRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *TeardownDeploymentRequest) Reset()                    { *m = TeardownDeploymentRequest{} }
func (m *TeardownDeploymentRequest) String() string            { return proto.CompactTextString(m) }
func (*TeardownDeploymentRequest) ProtoMessage()               {}
func (*TeardownDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *TeardownDeploymentRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*ListDeploymentRequest)(nil), "soapbox.ListDeploymentRequest")
	proto.RegisterType((*ListDeploymentResponse)(nil), "soapbox.ListDeploymentResponse")
	proto.RegisterType((*GetDeploymentRequest)(nil), "soapbox.GetDeploymentRequest")
	proto.RegisterType((*Deployment)(nil), "soapbox.Deployment")
	proto.RegisterType((*StartDeploymentResponse)(nil), "soapbox.StartDeploymentResponse")
	proto.RegisterType((*GetDeploymentStatusRequest)(nil), "soapbox.GetDeploymentStatusRequest")
	proto.RegisterType((*GetDeploymentStatusResponse)(nil), "soapbox.GetDeploymentStatusResponse")
	proto.RegisterType((*TeardownDeploymentRequest)(nil), "soapbox.TeardownDeploymentRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Deployments service

type DeploymentsClient interface {
	ListDeployments(ctx context.Context, in *ListDeploymentRequest, opts ...grpc.CallOption) (*ListDeploymentResponse, error)
	GetDeployment(ctx context.Context, in *GetDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error)
	StartDeployment(ctx context.Context, in *Deployment, opts ...grpc.CallOption) (*StartDeploymentResponse, error)
	GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error)
	TeardownDeployment(ctx context.Context, in *TeardownDeploymentRequest, opts ...grpc.CallOption) (*Empty, error)
}

type deploymentsClient struct {
	cc *grpc.ClientConn
}

func NewDeploymentsClient(cc *grpc.ClientConn) DeploymentsClient {
	return &deploymentsClient{cc}
}

func (c *deploymentsClient) ListDeployments(ctx context.Context, in *ListDeploymentRequest, opts ...grpc.CallOption) (*ListDeploymentResponse, error) {
	out := new(ListDeploymentResponse)
	err := grpc.Invoke(ctx, "/soapbox.Deployments/ListDeployments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsClient) GetDeployment(ctx context.Context, in *GetDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error) {
	out := new(Deployment)
	err := grpc.Invoke(ctx, "/soapbox.Deployments/GetDeployment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsClient) StartDeployment(ctx context.Context, in *Deployment, opts ...grpc.CallOption) (*StartDeploymentResponse, error) {
	out := new(StartDeploymentResponse)
	err := grpc.Invoke(ctx, "/soapbox.Deployments/StartDeployment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsClient) GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error) {
	out := new(GetDeploymentStatusResponse)
	err := grpc.Invoke(ctx, "/soapbox.Deployments/GetDeploymentStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsClient) TeardownDeployment(ctx context.Context, in *TeardownDeploymentRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/soapbox.Deployments/TeardownDeployment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Deployments service

type DeploymentsServer interface {
	ListDeployments(context.Context, *ListDeploymentRequest) (*ListDeploymentResponse, error)
	GetDeployment(context.Context, *GetDeploymentRequest) (*Deployment, error)
	StartDeployment(context.Context, *Deployment) (*StartDeploymentResponse, error)
	GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error)
	TeardownDeployment(context.Context, *TeardownDeploymentRequest) (*Empty, error)
}

func RegisterDeploymentsServer(s *grpc.Server, srv DeploymentsServer) {
	s.RegisterService(&_Deployments_serviceDesc, srv)
}

func _Deployments_ListDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).ListDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Deployments/ListDeployments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).ListDeployments(ctx, req.(*ListDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deployments_GetDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).GetDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Deployments/GetDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).GetDeployment(ctx, req.(*GetDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deployments_StartDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Deployment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).StartDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Deployments/StartDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).StartDeployment(ctx, req.(*Deployment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deployments_GetDeploymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).GetDeploymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Deployments/GetDeploymentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).GetDeploymentStatus(ctx, req.(*GetDeploymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deployments_TeardownDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeardownDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).TeardownDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Deployments/TeardownDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).TeardownDeployment(ctx, req.(*TeardownDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Deployments_serviceDesc = grpc.ServiceDesc{
	ServiceName: "soapbox.Deployments",
	HandlerType: (*DeploymentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDeployments",
			Handler:    _Deployments_ListDeployments_Handler,
		},
		{
			MethodName: "GetDeployment",
			Handler:    _Deployments_GetDeployment_Handler,
		},
		{
			MethodName: "StartDeployment",
			Handler:    _Deployments_StartDeployment_Handler,
		},
		{
			MethodName: "GetDeploymentStatus",
			Handler:    _Deployments_GetDeploymentStatus_Handler,
		},
		{
			MethodName: "TeardownDeployment",
			Handler:    _Deployments_TeardownDeployment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deployment.proto",
}

func init() { proto.RegisterFile("deployment.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x6d, 0x5a, 0x3a, 0xd4, 0x1b, 0xb5, 0x83, 0xbb, 0x02, 0xc1, 0x68, 0x23, 0x32, 0x30, 0x15,
	0x81, 0xf6, 0xd0, 0x09, 0x1e, 0x91, 0x86, 0x98, 0x10, 0x13, 0x12, 0x52, 0xb6, 0x27, 0x5e, 0x26,
	0xb7, 0xb1, 0x84, 0xa5, 0x35, 0x36, 0xf1, 0xdd, 0x60, 0x3f, 0xc4, 0xff, 0xf0, 0x47, 0x88, 0x36,
	0x73, 0x9c, 0xe0, 0xb0, 0xb7, 0xe4, 0xdc, 0x73, 0xaf, 0x8f, 0xcf, 0x3d, 0x32, 0xdc, 0xcb, 0xa5,
	0xb9, 0xd0, 0xd7, 0x2b, 0x59, 0xd0, 0x81, 0x29, 0x35, 0x69, 0xbc, 0x6b, 0xb5, 0x30, 0x0b, 0xfd,
	0x93, 0x8d, 0xab, 0x8f, 0x0d, 0xce, 0xee, 0x0b, 0x63, 0x2e, 0xd4, 0x52, 0x90, 0xd2, 0xc5, 0x0d,
	0x24, 0x8b, 0x2b, 0x55, 0xea, 0xa2, 0xee, 0xe6, 0xef, 0xe0, 0xc1, 0x67, 0x65, 0xe9, 0x83, 0x9b,
	0x9a, 0xc9, 0xef, 0x97, 0xd2, 0x12, 0xbe, 0x80, 0x89, 0x37, 0xe0, 0x5c, 0xe5, 0x49, 0x94, 0x46,
	0xb3, 0x61, 0x36, 0xf6, 0xd0, 0x4f, 0x39, 0xff, 0x02, 0x0f, 0xdb, 0xfd, 0xd6, 0xe8, 0xc2, 0x4a,
	0x7c, 0x03, 0x71, 0xad, 0xd5, 0x26, 0x51, 0x3a, 0x98, 0xc5, 0xf3, 0x9d, 0x83, 0x1b, 0x91, 0x5e,
	0x87, 0xcf, 0xe3, 0xfb, 0x30, 0xfd, 0x28, 0x03, 0x7a, 0x26, 0xd0, 0x77, 0x1a, 0xfa, 0x2a, 0xe7,
	0xbf, 0x23, 0x80, 0x9a, 0xd5, 0x2e, 0xe3, 0x5b, 0x88, 0x3d, 0xa1, 0x49, 0x3f, 0x8d, 0x66, 0xf1,
	0x7c, 0xea, 0x4e, 0x3f, 0xaa, 0x6b, 0x99, 0x4f, 0xc4, 0x7d, 0x18, 0xc8, 0xe2, 0x2a, 0x19, 0xb4,
	0xf8, 0xc7, 0xb5, 0x71, 0xd9, 0x5f, 0x02, 0xee, 0x01, 0x2c, 0xf5, 0x6a, 0xa5, 0x88, 0x94, 0xfd,
	0x96, 0xdc, 0x49, 0xa3, 0xd9, 0x28, 0xf3, 0x10, 0x9c, 0xc2, 0xd0, 0x92, 0x20, 0x99, 0x0c, 0xd7,
	0xa5, 0xcd, 0x0f, 0xee, 0x02, 0x2c, 0x4b, 0x29, 0x48, 0xe6, 0xe7, 0x82, 0x92, 0xad, 0x75, 0x69,
	0x54, 0x21, 0x47, 0xc4, 0x5f, 0xc2, 0xa3, 0x53, 0x12, 0x65, 0xc8, 0xcd, 0xf6, 0xf5, 0x5f, 0x03,
	0x6b, 0xd8, 0x74, 0x4a, 0x82, 0x2e, 0x6d, 0x97, 0x59, 0x87, 0xf0, 0x24, 0xc8, 0xae, 0x86, 0x3b,
	0xb1, 0x91, 0x27, 0x96, 0xbf, 0x82, 0xc7, 0x67, 0x52, 0x94, 0xb9, 0xfe, 0x51, 0xdc, 0xba, 0x8e,
	0xf9, 0xaf, 0x01, 0xc4, 0x35, 0xcb, 0xe2, 0x19, 0x6c, 0x37, 0x73, 0x61, 0x71, 0xcf, 0xb9, 0x19,
	0x4c, 0x1c, 0x7b, 0xda, 0x59, 0xdf, 0xc8, 0xe4, 0x3d, 0x3c, 0x86, 0x71, 0xe3, 0x1e, 0xb8, 0xeb,
	0x7a, 0x42, 0xa1, 0x61, 0xa1, 0xb8, 0xf1, 0x1e, 0x9e, 0xc0, 0x76, 0xcb, 0x67, 0x0c, 0x31, 0x59,
	0xea, 0xc0, 0x8e, 0xb5, 0xf0, 0x1e, 0x2e, 0x60, 0x27, 0x60, 0x2d, 0x3e, 0x0b, 0x0b, 0x6b, 0xac,
	0x89, 0x3d, 0xff, 0x3f, 0xc9, 0x9d, 0x71, 0x02, 0xf8, 0xef, 0x26, 0x90, 0xbb, 0xee, 0xce, 0x35,
	0xb1, 0x49, 0x9d, 0xe0, 0x95, 0xa1, 0x6b, 0xde, 0x7b, 0x1f, 0x7f, 0x1d, 0x55, 0x90, 0x59, 0x2c,
	0xb6, 0xd6, 0x8f, 0xc0, 0xe1, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0xba, 0x7f, 0x41, 0x56,
	0x04, 0x00, 0x00,
}
