// Code generated by protoc-gen-go. DO NOT EDIT.
// source: environment.proto

package soapboxpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ListEnvironmentRequest struct {
}

func (m *ListEnvironmentRequest) Reset()                    { *m = ListEnvironmentRequest{} }
func (m *ListEnvironmentRequest) String() string            { return proto.CompactTextString(m) }
func (*ListEnvironmentRequest) ProtoMessage()               {}
func (*ListEnvironmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type ListEnvironmentResponse struct {
	Environments []*Environment `protobuf:"bytes,1,rep,name=environments" json:"environments,omitempty"`
}

func (m *ListEnvironmentResponse) Reset()                    { *m = ListEnvironmentResponse{} }
func (m *ListEnvironmentResponse) String() string            { return proto.CompactTextString(m) }
func (*ListEnvironmentResponse) ProtoMessage()               {}
func (*ListEnvironmentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *ListEnvironmentResponse) GetEnvironments() []*Environment {
	if m != nil {
		return m.Environments
	}
	return nil
}

type GetEnvironmentRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetEnvironmentRequest) Reset()                    { *m = GetEnvironmentRequest{} }
func (m *GetEnvironmentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEnvironmentRequest) ProtoMessage()               {}
func (*GetEnvironmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *GetEnvironmentRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetEnvironmentResponse struct {
	Env *Environment `protobuf:"bytes,1,opt,name=env" json:"env,omitempty"`
}

func (m *GetEnvironmentResponse) Reset()                    { *m = GetEnvironmentResponse{} }
func (m *GetEnvironmentResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEnvironmentResponse) ProtoMessage()               {}
func (*GetEnvironmentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *GetEnvironmentResponse) GetEnv() *Environment {
	if m != nil {
		return m.Env
	}
	return nil
}

type Environment struct {
	Id        int32                  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Slug      string                 `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
	Vars      []*EnvironmentVariable `protobuf:"bytes,4,rep,name=vars" json:"vars,omitempty"`
	CreatedAt string                 `protobuf:"bytes,5,opt,name=createdAt" json:"createdAt,omitempty"`
}

func (m *Environment) Reset()                    { *m = Environment{} }
func (m *Environment) String() string            { return proto.CompactTextString(m) }
func (*Environment) ProtoMessage()               {}
func (*Environment) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *Environment) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Environment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Environment) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Environment) GetVars() []*EnvironmentVariable {
	if m != nil {
		return m.Vars
	}
	return nil
}

func (m *Environment) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type EnvironmentVariable struct {
	Id    int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *EnvironmentVariable) Reset()                    { *m = EnvironmentVariable{} }
func (m *EnvironmentVariable) String() string            { return proto.CompactTextString(m) }
func (*EnvironmentVariable) ProtoMessage()               {}
func (*EnvironmentVariable) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *EnvironmentVariable) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EnvironmentVariable) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *EnvironmentVariable) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CreateEnvironmentRequest struct {
	Name string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Slug string                 `protobuf:"bytes,2,opt,name=slug" json:"slug,omitempty"`
	Vars []*EnvironmentVariable `protobuf:"bytes,3,rep,name=vars" json:"vars,omitempty"`
}

func (m *CreateEnvironmentRequest) Reset()                    { *m = CreateEnvironmentRequest{} }
func (m *CreateEnvironmentRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateEnvironmentRequest) ProtoMessage()               {}
func (*CreateEnvironmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *CreateEnvironmentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateEnvironmentRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *CreateEnvironmentRequest) GetVars() []*EnvironmentVariable {
	if m != nil {
		return m.Vars
	}
	return nil
}

type CreateEnvironmentResponse struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateEnvironmentResponse) Reset()                    { *m = CreateEnvironmentResponse{} }
func (m *CreateEnvironmentResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateEnvironmentResponse) ProtoMessage()               {}
func (*CreateEnvironmentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *CreateEnvironmentResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DestroyEnvironmentRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DestroyEnvironmentRequest) Reset()                    { *m = DestroyEnvironmentRequest{} }
func (m *DestroyEnvironmentRequest) String() string            { return proto.CompactTextString(m) }
func (*DestroyEnvironmentRequest) ProtoMessage()               {}
func (*DestroyEnvironmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *DestroyEnvironmentRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DestroyEnvironmentResponse struct {
}

func (m *DestroyEnvironmentResponse) Reset()                    { *m = DestroyEnvironmentResponse{} }
func (m *DestroyEnvironmentResponse) String() string            { return proto.CompactTextString(m) }
func (*DestroyEnvironmentResponse) ProtoMessage()               {}
func (*DestroyEnvironmentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

type CopyEnvironmentRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CopyEnvironmentRequest) Reset()                    { *m = CopyEnvironmentRequest{} }
func (m *CopyEnvironmentRequest) String() string            { return proto.CompactTextString(m) }
func (*CopyEnvironmentRequest) ProtoMessage()               {}
func (*CopyEnvironmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *CopyEnvironmentRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CopyEnvironmentResponse struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CopyEnvironmentResponse) Reset()                    { *m = CopyEnvironmentResponse{} }
func (m *CopyEnvironmentResponse) String() string            { return proto.CompactTextString(m) }
func (*CopyEnvironmentResponse) ProtoMessage()               {}
func (*CopyEnvironmentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *CopyEnvironmentResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*ListEnvironmentRequest)(nil), "soapbox.ListEnvironmentRequest")
	proto.RegisterType((*ListEnvironmentResponse)(nil), "soapbox.ListEnvironmentResponse")
	proto.RegisterType((*GetEnvironmentRequest)(nil), "soapbox.GetEnvironmentRequest")
	proto.RegisterType((*GetEnvironmentResponse)(nil), "soapbox.GetEnvironmentResponse")
	proto.RegisterType((*Environment)(nil), "soapbox.Environment")
	proto.RegisterType((*EnvironmentVariable)(nil), "soapbox.EnvironmentVariable")
	proto.RegisterType((*CreateEnvironmentRequest)(nil), "soapbox.CreateEnvironmentRequest")
	proto.RegisterType((*CreateEnvironmentResponse)(nil), "soapbox.CreateEnvironmentResponse")
	proto.RegisterType((*DestroyEnvironmentRequest)(nil), "soapbox.DestroyEnvironmentRequest")
	proto.RegisterType((*DestroyEnvironmentResponse)(nil), "soapbox.DestroyEnvironmentResponse")
	proto.RegisterType((*CopyEnvironmentRequest)(nil), "soapbox.CopyEnvironmentRequest")
	proto.RegisterType((*CopyEnvironmentResponse)(nil), "soapbox.CopyEnvironmentResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Environments service

type EnvironmentsClient interface {
	ListEnvironments(ctx context.Context, in *ListEnvironmentRequest, opts ...grpc.CallOption) (*ListEnvironmentResponse, error)
	GetEnvironment(ctx context.Context, in *GetEnvironmentRequest, opts ...grpc.CallOption) (*GetEnvironmentResponse, error)
	CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*CreateEnvironmentResponse, error)
	DestroyEnvironment(ctx context.Context, in *DestroyEnvironmentRequest, opts ...grpc.CallOption) (*DestroyEnvironmentResponse, error)
	CopyEnvironment(ctx context.Context, in *CopyEnvironmentRequest, opts ...grpc.CallOption) (*CopyEnvironmentResponse, error)
}

type environmentsClient struct {
	cc *grpc.ClientConn
}

func NewEnvironmentsClient(cc *grpc.ClientConn) EnvironmentsClient {
	return &environmentsClient{cc}
}

func (c *environmentsClient) ListEnvironments(ctx context.Context, in *ListEnvironmentRequest, opts ...grpc.CallOption) (*ListEnvironmentResponse, error) {
	out := new(ListEnvironmentResponse)
	err := grpc.Invoke(ctx, "/soapbox.Environments/ListEnvironments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentsClient) GetEnvironment(ctx context.Context, in *GetEnvironmentRequest, opts ...grpc.CallOption) (*GetEnvironmentResponse, error) {
	out := new(GetEnvironmentResponse)
	err := grpc.Invoke(ctx, "/soapbox.Environments/GetEnvironment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentsClient) CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*CreateEnvironmentResponse, error) {
	out := new(CreateEnvironmentResponse)
	err := grpc.Invoke(ctx, "/soapbox.Environments/CreateEnvironment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentsClient) DestroyEnvironment(ctx context.Context, in *DestroyEnvironmentRequest, opts ...grpc.CallOption) (*DestroyEnvironmentResponse, error) {
	out := new(DestroyEnvironmentResponse)
	err := grpc.Invoke(ctx, "/soapbox.Environments/DestroyEnvironment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentsClient) CopyEnvironment(ctx context.Context, in *CopyEnvironmentRequest, opts ...grpc.CallOption) (*CopyEnvironmentResponse, error) {
	out := new(CopyEnvironmentResponse)
	err := grpc.Invoke(ctx, "/soapbox.Environments/CopyEnvironment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Environments service

type EnvironmentsServer interface {
	ListEnvironments(context.Context, *ListEnvironmentRequest) (*ListEnvironmentResponse, error)
	GetEnvironment(context.Context, *GetEnvironmentRequest) (*GetEnvironmentResponse, error)
	CreateEnvironment(context.Context, *CreateEnvironmentRequest) (*CreateEnvironmentResponse, error)
	DestroyEnvironment(context.Context, *DestroyEnvironmentRequest) (*DestroyEnvironmentResponse, error)
	CopyEnvironment(context.Context, *CopyEnvironmentRequest) (*CopyEnvironmentResponse, error)
}

func RegisterEnvironmentsServer(s *grpc.Server, srv EnvironmentsServer) {
	s.RegisterService(&_Environments_serviceDesc, srv)
}

func _Environments_ListEnvironments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentsServer).ListEnvironments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Environments/ListEnvironments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentsServer).ListEnvironments(ctx, req.(*ListEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environments_GetEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentsServer).GetEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Environments/GetEnvironment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentsServer).GetEnvironment(ctx, req.(*GetEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environments_CreateEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentsServer).CreateEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Environments/CreateEnvironment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentsServer).CreateEnvironment(ctx, req.(*CreateEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environments_DestroyEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentsServer).DestroyEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Environments/DestroyEnvironment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentsServer).DestroyEnvironment(ctx, req.(*DestroyEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environments_CopyEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentsServer).CopyEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Environments/CopyEnvironment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentsServer).CopyEnvironment(ctx, req.(*CopyEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Environments_serviceDesc = grpc.ServiceDesc{
	ServiceName: "soapbox.Environments",
	HandlerType: (*EnvironmentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEnvironments",
			Handler:    _Environments_ListEnvironments_Handler,
		},
		{
			MethodName: "GetEnvironment",
			Handler:    _Environments_GetEnvironment_Handler,
		},
		{
			MethodName: "CreateEnvironment",
			Handler:    _Environments_CreateEnvironment_Handler,
		},
		{
			MethodName: "DestroyEnvironment",
			Handler:    _Environments_DestroyEnvironment_Handler,
		},
		{
			MethodName: "CopyEnvironment",
			Handler:    _Environments_CopyEnvironment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "environment.proto",
}

func init() { proto.RegisterFile("environment.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0xc5, 0x36, 0xb4, 0x62, 0x40, 0x14, 0xb6, 0x14, 0x16, 0x0b, 0x15, 0x77, 0x2b, 0xb5, 0xae,
	0x90, 0x50, 0x45, 0x2f, 0x3d, 0xb6, 0xa5, 0x51, 0x2e, 0xc9, 0xc5, 0x48, 0x44, 0x8a, 0x22, 0x45,
	0x76, 0x58, 0x45, 0x56, 0xc0, 0xeb, 0x78, 0x17, 0x2b, 0x7c, 0x48, 0xbe, 0x2c, 0x3f, 0x14, 0xd9,
	0x38, 0xc6, 0xd8, 0x6b, 0xc4, 0x6d, 0x3d, 0xfb, 0xe6, 0xbd, 0x99, 0x79, 0xb3, 0x86, 0x0e, 0xf5,
	0x42, 0x37, 0x60, 0xde, 0x9a, 0x7a, 0x62, 0xe2, 0x07, 0x4c, 0x30, 0xf4, 0x9e, 0x33, 0xdb, 0x77,
	0xd8, 0x13, 0xc1, 0xd0, 0xbb, 0x70, 0xb9, 0x38, 0xdb, 0x23, 0x2c, 0xfa, 0xb8, 0xa1, 0x5c, 0x90,
	0x39, 0xf4, 0x0b, 0x37, 0xdc, 0x67, 0x1e, 0xa7, 0xe8, 0x37, 0x34, 0x33, 0x94, 0x1c, 0x2b, 0x86,
	0x66, 0x36, 0xa6, 0xdd, 0x49, 0x42, 0x3a, 0xc9, 0xe6, 0x1c, 0x20, 0xc9, 0x77, 0xf8, 0x74, 0x4e,
	0x25, 0x6a, 0xa8, 0x05, 0xaa, 0xbb, 0xc4, 0x8a, 0xa1, 0x98, 0x35, 0x4b, 0x75, 0x97, 0xe4, 0x0f,
	0xf4, 0xf2, 0xc0, 0x44, 0xfc, 0x1b, 0x68, 0xd4, 0x0b, 0x63, 0x68, 0x99, 0x66, 0x04, 0x20, 0xcf,
	0x0a, 0x34, 0x32, 0xc1, 0xbc, 0x02, 0x42, 0x50, 0xf5, 0xec, 0x35, 0xc5, 0xaa, 0xa1, 0x98, 0x75,
	0x2b, 0x3e, 0x47, 0x31, 0xbe, 0xda, 0xdc, 0x63, 0x6d, 0x17, 0x8b, 0xce, 0xe8, 0x27, 0x54, 0x43,
	0x3b, 0xe0, 0xb8, 0x1a, 0x37, 0x39, 0x94, 0x09, 0x2e, 0xec, 0xc0, 0xb5, 0x9d, 0x15, 0xb5, 0x62,
	0x24, 0x1a, 0x42, 0xfd, 0x2e, 0xa0, 0xb6, 0xa0, 0xcb, 0xbf, 0x02, 0xd7, 0x62, 0xaa, 0x7d, 0x80,
	0x5c, 0xc2, 0x47, 0x49, 0x6a, 0xa1, 0xbc, 0x36, 0x68, 0x0f, 0x74, 0x9b, 0x54, 0x17, 0x1d, 0x51,
	0x17, 0x6a, 0xa1, 0xbd, 0xda, 0xd0, 0xa4, 0xba, 0xdd, 0x07, 0x11, 0x80, 0x67, 0x31, 0xb7, 0x64,
	0xa8, 0x6f, 0x2d, 0x2a, 0x92, 0x16, 0x55, 0x49, 0x8b, 0xda, 0xa9, 0x2d, 0x92, 0x31, 0x0c, 0x24,
	0xaa, 0x89, 0x43, 0x79, 0x2f, 0xc7, 0x30, 0xf8, 0x4f, 0xb9, 0x08, 0xd8, 0xf6, 0x04, 0xe3, 0x87,
	0xa0, 0xcb, 0xc0, 0x3b, 0x6a, 0x62, 0x42, 0x6f, 0xc6, 0xfc, 0x53, 0x78, 0x7e, 0x40, 0xbf, 0x80,
	0x94, 0xd7, 0x37, 0x7d, 0xd1, 0xa0, 0x99, 0xc1, 0x71, 0x74, 0x05, 0xed, 0xdc, 0xea, 0x73, 0x34,
	0x4a, 0xa7, 0x22, 0x7f, 0x2f, 0xba, 0x51, 0x0e, 0x48, 0x8a, 0xaf, 0xa0, 0x39, 0xb4, 0x0e, 0xb7,
	0x1a, 0x7d, 0x4e, 0xb3, 0xa4, 0xef, 0x42, 0x1f, 0x95, 0xde, 0xa7, 0xa4, 0x37, 0xd0, 0x29, 0x78,
	0x81, 0xbe, 0xa4, 0x79, 0x65, 0xdb, 0xa1, 0x93, 0x63, 0x90, 0x94, 0xfd, 0x16, 0x50, 0xd1, 0x0f,
	0xb4, 0xcf, 0x2d, 0x75, 0x56, 0xff, 0x7a, 0x14, 0x93, 0x0a, 0x2c, 0xe0, 0x43, 0xce, 0xa8, 0xcc,
	0xac, 0xe5, 0x66, 0x67, 0x66, 0x5d, 0xe2, 0x31, 0xa9, 0xfc, 0x6b, 0x5c, 0xd7, 0x13, 0x90, 0xef,
	0x38, 0xef, 0xe2, 0xdf, 0xde, 0xaf, 0xd7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x16, 0x51, 0x21,
	0x0b, 0x05, 0x00, 0x00,
}
