// Code generated by protoc-gen-go. DO NOT EDIT.
// source: soapbox.proto

/*
Package soapboxpb is a generated protocol buffer package.

It is generated from these files:
	soapbox.proto
	application.proto
	deployment.proto
	environment.proto

It has these top-level messages:
	Empty
	Application
	ListApplicationResponse
	GetApplicationRequest
	ListDeploymentRequest
	ListDeploymentResponse
	GetDeploymentRequest
	Deployment
	StartDeploymentResponse
	GetDeploymentStatusRequest
	GetDeploymentStatusResponse
	TeardownDeploymentRequest
	ListEnvironmentRequest
	ListEnvironmentResponse
	GetEnvironmentRequest
	Environment
	EnvironmentVariable
	DestroyEnvironmentRequest
	CopyEnvironmentRequest
*/
package soapboxpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Empty)(nil), "soapbox.Empty")
}

func init() { proto.RegisterFile("soapbox.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 65 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xce, 0x4f, 0x2c,
	0x48, 0xca, 0xaf, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xd8, 0xb9,
	0x58, 0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x9d, 0xb8, 0xa3, 0x38, 0xa1, 0x62, 0x05, 0x49, 0x49, 0x6c,
	0x60, 0x55, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x4f, 0x96, 0xc7, 0x36, 0x00, 0x00,
	0x00,
}
