// Code generated by protoc-gen-go. DO NOT EDIT.
// source: activity.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ActivityType int32

const (
	ActivityType_APPLICATION_CREATED   ActivityType = 0
	ActivityType_DEPLOYMENT_STARTED    ActivityType = 1
	ActivityType_DEPLOYMENT_SUCCESS    ActivityType = 2
	ActivityType_DEPLOYMENT_FAILURE    ActivityType = 3
	ActivityType_ENVIRONMENT_CREATED   ActivityType = 4
	ActivityType_ENVIRONMENT_DESTROYED ActivityType = 5
	ActivityType_APPLICATION_DELETED   ActivityType = 6
)

var ActivityType_name = map[int32]string{
	0: "APPLICATION_CREATED",
	1: "DEPLOYMENT_STARTED",
	2: "DEPLOYMENT_SUCCESS",
	3: "DEPLOYMENT_FAILURE",
	4: "ENVIRONMENT_CREATED",
	5: "ENVIRONMENT_DESTROYED",
	6: "APPLICATION_DELETED",
}
var ActivityType_value = map[string]int32{
	"APPLICATION_CREATED":   0,
	"DEPLOYMENT_STARTED":    1,
	"DEPLOYMENT_SUCCESS":    2,
	"DEPLOYMENT_FAILURE":    3,
	"ENVIRONMENT_CREATED":   4,
	"ENVIRONMENT_DESTROYED": 5,
	"APPLICATION_DELETED":   6,
}

func (x ActivityType) String() string {
	return proto.EnumName(ActivityType_name, int32(x))
}
func (ActivityType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_activity_5b943f9fc47dae12, []int{0}
}

type ListActivitiesResponse struct {
	Activities           []*Activity `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListActivitiesResponse) Reset()         { *m = ListActivitiesResponse{} }
func (m *ListActivitiesResponse) String() string { return proto.CompactTextString(m) }
func (*ListActivitiesResponse) ProtoMessage()    {}
func (*ListActivitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_activity_5b943f9fc47dae12, []int{0}
}
func (m *ListActivitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActivitiesResponse.Unmarshal(m, b)
}
func (m *ListActivitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActivitiesResponse.Marshal(b, m, deterministic)
}
func (dst *ListActivitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActivitiesResponse.Merge(dst, src)
}
func (m *ListActivitiesResponse) XXX_Size() int {
	return xxx_messageInfo_ListActivitiesResponse.Size(m)
}
func (m *ListActivitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActivitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListActivitiesResponse proto.InternalMessageInfo

func (m *ListActivitiesResponse) GetActivities() []*Activity {
	if m != nil {
		return m.Activities
	}
	return nil
}

type Activity struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 ActivityType         `protobuf:"varint,2,opt,name=type,proto3,enum=soapbox.ActivityType" json:"type,omitempty"`
	UserId               int32                `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApplicationId        int32                `protobuf:"varint,4,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	DeploymentId         int32                `protobuf:"varint,5,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	EnvironmentId        int32                `protobuf:"varint,6,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Activity) Reset()         { *m = Activity{} }
func (m *Activity) String() string { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()    {}
func (*Activity) Descriptor() ([]byte, []int) {
	return fileDescriptor_activity_5b943f9fc47dae12, []int{1}
}
func (m *Activity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Activity.Unmarshal(m, b)
}
func (m *Activity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Activity.Marshal(b, m, deterministic)
}
func (dst *Activity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Activity.Merge(dst, src)
}
func (m *Activity) XXX_Size() int {
	return xxx_messageInfo_Activity.Size(m)
}
func (m *Activity) XXX_DiscardUnknown() {
	xxx_messageInfo_Activity.DiscardUnknown(m)
}

var xxx_messageInfo_Activity proto.InternalMessageInfo

func (m *Activity) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Activity) GetType() ActivityType {
	if m != nil {
		return m.Type
	}
	return ActivityType_APPLICATION_CREATED
}

func (m *Activity) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Activity) GetApplicationId() int32 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *Activity) GetDeploymentId() int32 {
	if m != nil {
		return m.DeploymentId
	}
	return 0
}

func (m *Activity) GetEnvironmentId() int32 {
	if m != nil {
		return m.EnvironmentId
	}
	return 0
}

func (m *Activity) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*ListActivitiesResponse)(nil), "soapbox.ListActivitiesResponse")
	proto.RegisterType((*Activity)(nil), "soapbox.Activity")
	proto.RegisterEnum("soapbox.ActivityType", ActivityType_name, ActivityType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActivitiesClient is the client API for Activities service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActivitiesClient interface {
	AddActivity(ctx context.Context, in *Activity, opts ...grpc.CallOption) (*Empty, error)
	ListActivities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListActivitiesResponse, error)
	ListApplicationActivities(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error)
	ListDeploymentActivities(ctx context.Context, in *GetDeploymentRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error)
}

type activitiesClient struct {
	cc *grpc.ClientConn
}

func NewActivitiesClient(cc *grpc.ClientConn) ActivitiesClient {
	return &activitiesClient{cc}
}

func (c *activitiesClient) AddActivity(ctx context.Context, in *Activity, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/soapbox.Activities/AddActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesClient) ListActivities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListActivitiesResponse, error) {
	out := new(ListActivitiesResponse)
	err := c.cc.Invoke(ctx, "/soapbox.Activities/ListActivities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesClient) ListApplicationActivities(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error) {
	out := new(ListActivitiesResponse)
	err := c.cc.Invoke(ctx, "/soapbox.Activities/ListApplicationActivities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesClient) ListDeploymentActivities(ctx context.Context, in *GetDeploymentRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error) {
	out := new(ListActivitiesResponse)
	err := c.cc.Invoke(ctx, "/soapbox.Activities/ListDeploymentActivities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivitiesServer is the server API for Activities service.
type ActivitiesServer interface {
	AddActivity(context.Context, *Activity) (*Empty, error)
	ListActivities(context.Context, *Empty) (*ListActivitiesResponse, error)
	ListApplicationActivities(context.Context, *GetApplicationRequest) (*ListActivitiesResponse, error)
	ListDeploymentActivities(context.Context, *GetDeploymentRequest) (*ListActivitiesResponse, error)
}

func RegisterActivitiesServer(s *grpc.Server, srv ActivitiesServer) {
	s.RegisterService(&_Activities_serviceDesc, srv)
}

func _Activities_AddActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Activity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServer).AddActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Activities/AddActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServer).AddActivity(ctx, req.(*Activity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activities_ListActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServer).ListActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Activities/ListActivities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServer).ListActivities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activities_ListApplicationActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServer).ListApplicationActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Activities/ListApplicationActivities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServer).ListApplicationActivities(ctx, req.(*GetApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activities_ListDeploymentActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServer).ListDeploymentActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Activities/ListDeploymentActivities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServer).ListDeploymentActivities(ctx, req.(*GetDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Activities_serviceDesc = grpc.ServiceDesc{
	ServiceName: "soapbox.Activities",
	HandlerType: (*ActivitiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddActivity",
			Handler:    _Activities_AddActivity_Handler,
		},
		{
			MethodName: "ListActivities",
			Handler:    _Activities_ListActivities_Handler,
		},
		{
			MethodName: "ListApplicationActivities",
			Handler:    _Activities_ListApplicationActivities_Handler,
		},
		{
			MethodName: "ListDeploymentActivities",
			Handler:    _Activities_ListDeploymentActivities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity.proto",
}

func init() { proto.RegisterFile("activity.proto", fileDescriptor_activity_5b943f9fc47dae12) }

var fileDescriptor_activity_5b943f9fc47dae12 = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0xd2, 0x2f, 0xb8, 0x5d, 0xa3, 0xce, 0x68, 0x5b, 0x56, 0x09, 0x56, 0x15, 0x21, 0x15,
	0x1e, 0x3a, 0x51, 0x9e, 0x78, 0x0c, 0x8d, 0x41, 0x11, 0xa5, 0xad, 0xdc, 0x0c, 0x69, 0x08, 0x51,
	0x65, 0xb5, 0x99, 0x2c, 0xb5, 0xb5, 0x69, 0xdc, 0x89, 0xfc, 0x07, 0x7e, 0x12, 0x6f, 0xfc, 0x31,
	0x94, 0x6f, 0xd3, 0xf1, 0xb0, 0xa7, 0xe4, 0x9e, 0x73, 0xee, 0xb9, 0xf6, 0xf5, 0x01, 0x2b, 0x58,
	0x29, 0x7e, 0xc7, 0x55, 0x34, 0x94, 0x3b, 0xa1, 0x04, 0x6a, 0x86, 0x22, 0x90, 0x37, 0xe2, 0x67,
	0xb7, 0x9d, 0xfd, 0xa4, 0x78, 0xf7, 0x38, 0x90, 0x72, 0xcd, 0x57, 0x81, 0xe2, 0x62, 0x9b, 0x41,
	0x1d, 0xca, 0xe4, 0x5a, 0x44, 0x1b, 0xb6, 0x55, 0x19, 0x72, 0x71, 0x2b, 0xc4, 0xed, 0x9a, 0x5d,
	0x26, 0xd5, 0xcd, 0xfe, 0xfb, 0xa5, 0xe2, 0x1b, 0x16, 0xaa, 0x60, 0x23, 0x53, 0x41, 0xff, 0x23,
	0x9c, 0x4e, 0x78, 0xa8, 0x9c, 0x74, 0x26, 0x67, 0x21, 0x61, 0xa1, 0x14, 0xdb, 0x90, 0xa1, 0xd7,
	0x00, 0x41, 0x81, 0xda, 0x46, 0xaf, 0x3a, 0x68, 0x8d, 0x8e, 0x87, 0xf9, 0x19, 0xb2, 0x86, 0x88,
	0x68, 0xa2, 0xfe, 0x2f, 0x13, 0x1e, 0xe5, 0x04, 0xb2, 0xc0, 0xe4, 0xd4, 0x36, 0x7a, 0xc6, 0xa0,
	0x4e, 0x4c, 0x4e, 0xd1, 0x4b, 0xa8, 0xa9, 0x48, 0x32, 0xdb, 0xec, 0x19, 0x03, 0x6b, 0x74, 0x72,
	0xcf, 0xc9, 0x8f, 0x24, 0x23, 0x89, 0x04, 0x9d, 0x41, 0x73, 0x1f, 0xb2, 0xdd, 0x92, 0x53, 0xbb,
	0x9a, 0xf4, 0x37, 0xe2, 0xd2, 0xa3, 0xe8, 0x05, 0x58, 0xda, 0xad, 0x63, 0xbe, 0x96, 0xf0, 0x6d,
	0x0d, 0xf5, 0x28, 0x7a, 0x0e, 0xed, 0x72, 0x13, 0xb1, 0xaa, 0x9e, 0xa8, 0x8e, 0x4a, 0x30, 0xf5,
	0x62, 0xdb, 0x3b, 0xbe, 0x13, 0xdb, 0x5c, 0xd5, 0x48, 0xbd, 0x34, 0xd4, 0xa3, 0xe8, 0x2d, 0xc0,
	0x6a, 0xc7, 0x02, 0xc5, 0xe8, 0x32, 0x50, 0x76, 0xb3, 0x67, 0x0c, 0x5a, 0xa3, 0xee, 0x30, 0x5d,
	0xeb, 0x30, 0x5f, 0xeb, 0xd0, 0xcf, 0xd7, 0x4a, 0x1e, 0x67, 0x6a, 0x47, 0xbd, 0xfa, 0x6d, 0xc0,
	0x91, 0x7e, 0x3b, 0x74, 0x06, 0x4f, 0x9c, 0xf9, 0x7c, 0xe2, 0x8d, 0x1d, 0xdf, 0x9b, 0x4d, 0x97,
	0x63, 0x82, 0x1d, 0x1f, 0xbb, 0x9d, 0x0a, 0x3a, 0x05, 0xe4, 0xe2, 0xf9, 0x64, 0x76, 0xfd, 0x09,
	0x4f, 0xfd, 0xe5, 0xc2, 0x77, 0x48, 0x8c, 0x1b, 0x87, 0xf8, 0xd5, 0x78, 0x8c, 0x17, 0x8b, 0x8e,
	0x79, 0x80, 0xbf, 0x77, 0xbc, 0xc9, 0x15, 0xc1, 0x9d, 0x6a, 0x3c, 0x00, 0x4f, 0x3f, 0x7b, 0x64,
	0x36, 0x4d, 0x88, 0x7c, 0x40, 0x0d, 0x9d, 0xc3, 0x89, 0x4e, 0xb8, 0x78, 0xe1, 0x93, 0xd9, 0x35,
	0x76, 0x3b, 0xf5, 0xc3, 0x43, 0xb9, 0x78, 0x82, 0xe3, 0x9e, 0xc6, 0xe8, 0x8f, 0x09, 0x50, 0xe6,
	0x02, 0x8d, 0xa0, 0xe5, 0x50, 0x5a, 0x3c, 0xef, 0xfd, 0x28, 0x74, 0xad, 0x02, 0xc2, 0x1b, 0xa9,
	0xa2, 0x7e, 0x05, 0x8d, 0xc1, 0xfa, 0x37, 0x5d, 0xe8, 0x40, 0xd3, 0xbd, 0x28, 0xea, 0xff, 0xc7,
	0xb0, 0x5f, 0x41, 0xdf, 0xe0, 0x3c, 0xe1, 0xca, 0x27, 0xd6, 0xfc, 0x9e, 0x15, 0xfd, 0x1f, 0x98,
	0x2e, 0x21, 0xec, 0xc7, 0x9e, 0x85, 0xea, 0x21, 0xfe, 0x5f, 0xc1, 0x8e, 0x39, 0xb7, 0x08, 0x87,
	0x66, 0xff, 0x54, 0xb7, 0x2f, 0x15, 0x0f, 0x77, 0x7f, 0xd7, 0xfc, 0x52, 0x4f, 0x53, 0xd2, 0x48,
	0x3e, 0x6f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x42, 0xe2, 0xcd, 0x4e, 0xe0, 0x03, 0x00, 0x00,
}
