// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ApplicationType int32

const (
	ApplicationType_SERVER  ApplicationType = 0
	ApplicationType_CRONJOB ApplicationType = 1
)

var ApplicationType_name = map[int32]string{
	0: "SERVER",
	1: "CRONJOB",
}
var ApplicationType_value = map[string]int32{
	"SERVER":  0,
	"CRONJOB": 1,
}

func (x ApplicationType) String() string {
	return proto1.EnumName(ApplicationType_name, int32(x))
}
func (ApplicationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type MetricType int32

const (
	MetricType_REQUEST_COUNT  MetricType = 0
	MetricType_LATENCY        MetricType = 1
	MetricType_HTTP_5XX_COUNT MetricType = 2
	MetricType_HTTP_4XX_COUNT MetricType = 3
	MetricType_HTTP_2XX_COUNT MetricType = 4
)

var MetricType_name = map[int32]string{
	0: "REQUEST_COUNT",
	1: "LATENCY",
	2: "HTTP_5XX_COUNT",
	3: "HTTP_4XX_COUNT",
	4: "HTTP_2XX_COUNT",
}
var MetricType_value = map[string]int32{
	"REQUEST_COUNT":  0,
	"LATENCY":        1,
	"HTTP_5XX_COUNT": 2,
	"HTTP_4XX_COUNT": 3,
	"HTTP_2XX_COUNT": 4,
}

func (x MetricType) String() string {
	return proto1.EnumName(MetricType_name, int32(x))
}
func (MetricType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type CreationState int32

const (
	CreationState_CREATE_INFRASTRUCTURE_WAIT CreationState = 0
	CreationState_SUCCEEDED                  CreationState = 1
	CreationState_FAILED                     CreationState = 2
)

var CreationState_name = map[int32]string{
	0: "CREATE_INFRASTRUCTURE_WAIT",
	1: "SUCCEEDED",
	2: "FAILED",
}
var CreationState_value = map[string]int32{
	"CREATE_INFRASTRUCTURE_WAIT": 0,
	"SUCCEEDED":                  1,
	"FAILED":                     2,
}

func (x CreationState) String() string {
	return proto1.EnumName(CreationState_name, int32(x))
}
func (CreationState) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type Application struct {
	Id                 int32                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserId             int32                      `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Name               string                     `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description        string                     `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	ExternalDns        string                     `protobuf:"bytes,5,opt,name=external_dns,json=externalDns" json:"external_dns,omitempty"`
	GithubRepoUrl      string                     `protobuf:"bytes,6,opt,name=github_repo_url,json=githubRepoUrl" json:"github_repo_url,omitempty"`
	DockerfilePath     string                     `protobuf:"bytes,7,opt,name=dockerfile_path,json=dockerfilePath" json:"dockerfile_path,omitempty"`
	EntrypointOverride string                     `protobuf:"bytes,8,opt,name=entrypoint_override,json=entrypointOverride" json:"entrypoint_override,omitempty"`
	Type               ApplicationType            `protobuf:"varint,9,opt,name=type,enum=soapbox.ApplicationType" json:"type,omitempty"`
	CreatedAt          *google_protobuf.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Slug               string                     `protobuf:"bytes,11,opt,name=slug" json:"slug,omitempty"`
	InternalDns        string                     `protobuf:"bytes,12,opt,name=internal_dns,json=internalDns" json:"internal_dns,omitempty"`
	CreationState      CreationState              `protobuf:"varint,13,opt,name=creation_state,json=creationState,enum=soapbox.CreationState" json:"creation_state,omitempty"`
}

func (m *Application) Reset()                    { *m = Application{} }
func (m *Application) String() string            { return proto1.CompactTextString(m) }
func (*Application) ProtoMessage()               {}
func (*Application) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Application) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Application) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Application) GetExternalDns() string {
	if m != nil {
		return m.ExternalDns
	}
	return ""
}

func (m *Application) GetGithubRepoUrl() string {
	if m != nil {
		return m.GithubRepoUrl
	}
	return ""
}

func (m *Application) GetDockerfilePath() string {
	if m != nil {
		return m.DockerfilePath
	}
	return ""
}

func (m *Application) GetEntrypointOverride() string {
	if m != nil {
		return m.EntrypointOverride
	}
	return ""
}

func (m *Application) GetType() ApplicationType {
	if m != nil {
		return m.Type
	}
	return ApplicationType_SERVER
}

func (m *Application) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Application) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Application) GetInternalDns() string {
	if m != nil {
		return m.InternalDns
	}
	return ""
}

func (m *Application) GetCreationState() CreationState {
	if m != nil {
		return m.CreationState
	}
	return CreationState_CREATE_INFRASTRUCTURE_WAIT
}

type ListApplicationRequest struct {
	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *ListApplicationRequest) Reset()                    { *m = ListApplicationRequest{} }
func (m *ListApplicationRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListApplicationRequest) ProtoMessage()               {}
func (*ListApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ListApplicationRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ListApplicationResponse struct {
	Applications []*Application `protobuf:"bytes,1,rep,name=applications" json:"applications,omitempty"`
}

func (m *ListApplicationResponse) Reset()                    { *m = ListApplicationResponse{} }
func (m *ListApplicationResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListApplicationResponse) ProtoMessage()               {}
func (*ListApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ListApplicationResponse) GetApplications() []*Application {
	if m != nil {
		return m.Applications
	}
	return nil
}

type GetApplicationRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetApplicationRequest) Reset()                    { *m = GetApplicationRequest{} }
func (m *GetApplicationRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetApplicationRequest) ProtoMessage()               {}
func (*GetApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GetApplicationRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ApplicationMetric struct {
	Time  string `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	Count int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *ApplicationMetric) Reset()                    { *m = ApplicationMetric{} }
func (m *ApplicationMetric) String() string            { return proto1.CompactTextString(m) }
func (*ApplicationMetric) ProtoMessage()               {}
func (*ApplicationMetric) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ApplicationMetric) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *ApplicationMetric) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ApplicationMetricsResponse struct {
	Metrics []*ApplicationMetric `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
}

func (m *ApplicationMetricsResponse) Reset()                    { *m = ApplicationMetricsResponse{} }
func (m *ApplicationMetricsResponse) String() string            { return proto1.CompactTextString(m) }
func (*ApplicationMetricsResponse) ProtoMessage()               {}
func (*ApplicationMetricsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ApplicationMetricsResponse) GetMetrics() []*ApplicationMetric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type GetApplicationMetricsRequest struct {
	Id         int32      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	MetricType MetricType `protobuf:"varint,2,opt,name=metric_type,json=metricType,enum=soapbox.MetricType" json:"metric_type,omitempty"`
}

func (m *GetApplicationMetricsRequest) Reset()                    { *m = GetApplicationMetricsRequest{} }
func (m *GetApplicationMetricsRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetApplicationMetricsRequest) ProtoMessage()               {}
func (*GetApplicationMetricsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *GetApplicationMetricsRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetApplicationMetricsRequest) GetMetricType() MetricType {
	if m != nil {
		return m.MetricType
	}
	return MetricType_REQUEST_COUNT
}

func init() {
	proto1.RegisterType((*Application)(nil), "soapbox.Application")
	proto1.RegisterType((*ListApplicationRequest)(nil), "soapbox.ListApplicationRequest")
	proto1.RegisterType((*ListApplicationResponse)(nil), "soapbox.ListApplicationResponse")
	proto1.RegisterType((*GetApplicationRequest)(nil), "soapbox.GetApplicationRequest")
	proto1.RegisterType((*ApplicationMetric)(nil), "soapbox.ApplicationMetric")
	proto1.RegisterType((*ApplicationMetricsResponse)(nil), "soapbox.ApplicationMetricsResponse")
	proto1.RegisterType((*GetApplicationMetricsRequest)(nil), "soapbox.GetApplicationMetricsRequest")
	proto1.RegisterEnum("soapbox.ApplicationType", ApplicationType_name, ApplicationType_value)
	proto1.RegisterEnum("soapbox.MetricType", MetricType_name, MetricType_value)
	proto1.RegisterEnum("soapbox.CreationState", CreationState_name, CreationState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Applications service

type ApplicationsClient interface {
	ListApplications(ctx context.Context, in *ListApplicationRequest, opts ...grpc.CallOption) (*ListApplicationResponse, error)
	CreateApplication(ctx context.Context, in *Application, opts ...grpc.CallOption) (*Application, error)
	GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*Application, error)
	GetApplicationMetrics(ctx context.Context, in *GetApplicationMetricsRequest, opts ...grpc.CallOption) (*ApplicationMetricsResponse, error)
}

type applicationsClient struct {
	cc *grpc.ClientConn
}

func NewApplicationsClient(cc *grpc.ClientConn) ApplicationsClient {
	return &applicationsClient{cc}
}

func (c *applicationsClient) ListApplications(ctx context.Context, in *ListApplicationRequest, opts ...grpc.CallOption) (*ListApplicationResponse, error) {
	out := new(ListApplicationResponse)
	err := grpc.Invoke(ctx, "/soapbox.Applications/ListApplications", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationsClient) CreateApplication(ctx context.Context, in *Application, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := grpc.Invoke(ctx, "/soapbox.Applications/CreateApplication", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationsClient) GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := grpc.Invoke(ctx, "/soapbox.Applications/GetApplication", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationsClient) GetApplicationMetrics(ctx context.Context, in *GetApplicationMetricsRequest, opts ...grpc.CallOption) (*ApplicationMetricsResponse, error) {
	out := new(ApplicationMetricsResponse)
	err := grpc.Invoke(ctx, "/soapbox.Applications/GetApplicationMetrics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Applications service

type ApplicationsServer interface {
	ListApplications(context.Context, *ListApplicationRequest) (*ListApplicationResponse, error)
	CreateApplication(context.Context, *Application) (*Application, error)
	GetApplication(context.Context, *GetApplicationRequest) (*Application, error)
	GetApplicationMetrics(context.Context, *GetApplicationMetricsRequest) (*ApplicationMetricsResponse, error)
}

func RegisterApplicationsServer(s *grpc.Server, srv ApplicationsServer) {
	s.RegisterService(&_Applications_serviceDesc, srv)
}

func _Applications_ListApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).ListApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Applications/ListApplications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).ListApplications(ctx, req.(*ListApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applications_CreateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Application)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).CreateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Applications/CreateApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).CreateApplication(ctx, req.(*Application))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applications_GetApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).GetApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Applications/GetApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).GetApplication(ctx, req.(*GetApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applications_GetApplicationMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).GetApplicationMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Applications/GetApplicationMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).GetApplicationMetrics(ctx, req.(*GetApplicationMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Applications_serviceDesc = grpc.ServiceDesc{
	ServiceName: "soapbox.Applications",
	HandlerType: (*ApplicationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListApplications",
			Handler:    _Applications_ListApplications_Handler,
		},
		{
			MethodName: "CreateApplication",
			Handler:    _Applications_CreateApplication_Handler,
		},
		{
			MethodName: "GetApplication",
			Handler:    _Applications_GetApplication_Handler,
		},
		{
			MethodName: "GetApplicationMetrics",
			Handler:    _Applications_GetApplicationMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application.proto",
}

func init() { proto1.RegisterFile("application.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 745 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x5d, 0x6f, 0xe2, 0x56,
	0x10, 0x8d, 0xf9, 0x2c, 0xc3, 0x47, 0xe0, 0x26, 0x4d, 0x2c, 0xab, 0x4a, 0xa8, 0xab, 0x36, 0x08,
	0x55, 0x44, 0xa5, 0xa9, 0xd4, 0x3e, 0xe4, 0xc1, 0x31, 0x4e, 0x43, 0x94, 0x85, 0xec, 0xc5, 0x6c,
	0xb2, 0xfb, 0x62, 0x39, 0xf8, 0x06, 0xac, 0x05, 0xdb, 0xeb, 0x7b, 0x59, 0x25, 0xbf, 0x75, 0xff,
	0xc4, 0xfe, 0x84, 0x95, 0xaf, 0x8d, 0x31, 0xc4, 0x3c, 0x31, 0xf7, 0xcc, 0x99, 0x61, 0xe6, 0xcc,
	0x91, 0xa1, 0x61, 0x7a, 0xde, 0xdc, 0x9e, 0x98, 0xcc, 0x76, 0x9d, 0x8e, 0xe7, 0xbb, 0xcc, 0x45,
	0x45, 0xea, 0x9a, 0xde, 0x93, 0xfb, 0x22, 0x55, 0xa3, 0x20, 0xc4, 0xa5, 0xd3, 0xa9, 0xeb, 0x4e,
	0xe7, 0xe4, 0x9c, 0xbf, 0x9e, 0x96, 0xcf, 0xe7, 0xcc, 0x5e, 0x10, 0xca, 0xcc, 0x85, 0x17, 0x12,
	0xe4, 0xef, 0x59, 0x28, 0x2b, 0xeb, 0x76, 0xa8, 0x06, 0x19, 0xdb, 0x12, 0x85, 0xa6, 0xd0, 0xca,
	0xe3, 0x8c, 0x6d, 0xa1, 0x63, 0x28, 0x2e, 0x29, 0xf1, 0x0d, 0xdb, 0x12, 0x33, 0x1c, 0x2c, 0x04,
	0xcf, 0xbe, 0x85, 0x10, 0xe4, 0x1c, 0x73, 0x41, 0xc4, 0x6c, 0x53, 0x68, 0x95, 0x30, 0x8f, 0x51,
	0x13, 0xca, 0x16, 0xa1, 0x13, 0xdf, 0xf6, 0x82, 0x5e, 0x62, 0x8e, 0xa7, 0x92, 0x10, 0xfa, 0x15,
	0x2a, 0xe4, 0x85, 0x11, 0xdf, 0x31, 0xe7, 0x86, 0xe5, 0x50, 0x31, 0x1f, 0x52, 0x56, 0x58, 0xcf,
	0xa1, 0xe8, 0x0f, 0xd8, 0x9f, 0xda, 0x6c, 0xb6, 0x7c, 0x32, 0x7c, 0xe2, 0xb9, 0xc6, 0xd2, 0x9f,
	0x8b, 0x05, 0xce, 0xaa, 0x86, 0x30, 0x26, 0x9e, 0x3b, 0xf6, 0xe7, 0xe8, 0x0c, 0xf6, 0x2d, 0x77,
	0xf2, 0x99, 0xf8, 0xcf, 0xf6, 0x9c, 0x18, 0x9e, 0xc9, 0x66, 0x62, 0x91, 0xf3, 0x6a, 0x6b, 0xf8,
	0xde, 0x64, 0x33, 0x74, 0x0e, 0x07, 0xc4, 0x61, 0xfe, 0xab, 0xe7, 0xda, 0x0e, 0x33, 0xdc, 0xaf,
	0xc4, 0xf7, 0x6d, 0x8b, 0x88, 0x3f, 0x71, 0x32, 0x5a, 0xa7, 0x86, 0x51, 0x06, 0xfd, 0x09, 0x39,
	0xf6, 0xea, 0x11, 0xb1, 0xd4, 0x14, 0x5a, 0xb5, 0xae, 0xd8, 0x59, 0x49, 0x9a, 0xd0, 0x49, 0x7f,
	0xf5, 0x08, 0xe6, 0x2c, 0xf4, 0x1f, 0xc0, 0xc4, 0x27, 0x26, 0x23, 0x96, 0x61, 0x32, 0x11, 0x9a,
	0x42, 0xab, 0xdc, 0x95, 0x3a, 0xa1, 0xee, 0x9d, 0x95, 0xee, 0x1d, 0x7d, 0xa5, 0x3b, 0x2e, 0x45,
	0x6c, 0x85, 0x05, 0x1a, 0xd2, 0xf9, 0x72, 0x2a, 0x96, 0x43, 0x0d, 0x83, 0x38, 0x50, 0xc8, 0x76,
	0x12, 0x0a, 0x55, 0x42, 0x85, 0x56, 0x58, 0xa0, 0xd0, 0x25, 0xd4, 0x78, 0x0f, 0xdb, 0x75, 0x0c,
	0xca, 0x4c, 0x46, 0xc4, 0x2a, 0x9f, 0xf4, 0x28, 0x9e, 0x54, 0x8d, 0xd2, 0xa3, 0x20, 0x8b, 0xab,
	0x93, 0xe4, 0x53, 0xfe, 0x0b, 0x8e, 0xee, 0x6c, 0xca, 0x12, 0xdb, 0x60, 0xf2, 0x65, 0x49, 0x28,
	0x4b, 0x1e, 0x5b, 0x48, 0x1e, 0x5b, 0x1e, 0xc1, 0xf1, 0x9b, 0x12, 0xea, 0xb9, 0x0e, 0x25, 0xe8,
	0x5f, 0xa8, 0x24, 0xec, 0x48, 0x45, 0xa1, 0x99, 0x6d, 0x95, 0xbb, 0x87, 0x69, 0xa2, 0xe1, 0x0d,
	0xa6, 0x7c, 0x06, 0x3f, 0xff, 0x4f, 0xd2, 0xc6, 0xd8, 0xf2, 0xa0, 0x7c, 0x09, 0x8d, 0x04, 0xeb,
	0x1d, 0x61, 0xbe, 0x3d, 0x09, 0xb4, 0x0b, 0xbc, 0xcc, 0x69, 0x25, 0xcc, 0x63, 0x74, 0x08, 0xf9,
	0x89, 0xbb, 0x74, 0x58, 0x64, 0xd5, 0xf0, 0x21, 0x63, 0x90, 0xde, 0x94, 0xd3, 0x78, 0xfe, 0x0b,
	0x28, 0x2e, 0x42, 0x28, 0x1a, 0x5d, 0x4a, 0x1b, 0x3d, 0xac, 0xc2, 0x2b, 0xaa, 0x6c, 0xc1, 0x2f,
	0x9b, 0xb3, 0xc7, 0x6d, 0x53, 0x57, 0x40, 0x17, 0x50, 0x0e, 0x4b, 0x0d, 0xee, 0xac, 0x0c, 0xbf,
	0xd7, 0x41, 0xfc, 0x4f, 0x61, 0x35, 0x37, 0x15, 0x2c, 0xe2, 0xb8, 0xdd, 0x86, 0xfd, 0x2d, 0xcf,
	0x21, 0x80, 0xc2, 0x48, 0xc3, 0x1f, 0x34, 0x5c, 0xdf, 0x43, 0x65, 0x28, 0xaa, 0x78, 0x38, 0xb8,
	0x1d, 0x5e, 0xd5, 0x85, 0xf6, 0x0c, 0x60, 0xdd, 0x05, 0x35, 0xa0, 0x8a, 0xb5, 0xf7, 0x63, 0x6d,
	0xa4, 0x1b, 0xea, 0x70, 0x3c, 0xd0, 0x43, 0xf6, 0x9d, 0xa2, 0x6b, 0x03, 0xf5, 0x63, 0x5d, 0x40,
	0x08, 0x6a, 0x37, 0xba, 0x7e, 0x6f, 0xfc, 0xf3, 0xf8, 0x18, 0x11, 0x32, 0x31, 0x76, 0x11, 0x63,
	0xd9, 0x18, 0xeb, 0xc6, 0x58, 0xae, 0x7d, 0x0b, 0xd5, 0x0d, 0x7f, 0xa1, 0x13, 0x90, 0x54, 0xac,
	0x29, 0xba, 0x66, 0xf4, 0x07, 0xd7, 0x58, 0x19, 0xe9, 0x78, 0xac, 0xea, 0x63, 0xac, 0x19, 0x0f,
	0x4a, 0x3f, 0xf8, 0xe7, 0x2a, 0x94, 0x46, 0x63, 0x55, 0xd5, 0xb4, 0x9e, 0xd6, 0xab, 0x0b, 0xc1,
	0x0a, 0xd7, 0x4a, 0xff, 0x4e, 0xeb, 0xd5, 0x33, 0xdd, 0x6f, 0x19, 0xa8, 0x24, 0x56, 0xa4, 0xe8,
	0x01, 0xea, 0x5b, 0x4e, 0xa3, 0xe8, 0x34, 0xd6, 0x29, 0xdd, 0xb7, 0x52, 0x73, 0x37, 0x21, 0xbc,
	0xb2, 0xbc, 0x87, 0x14, 0x68, 0xf0, 0xa9, 0x49, 0xf2, 0x6b, 0x97, 0x6a, 0x53, 0x29, 0x15, 0x95,
	0xf7, 0xd0, 0x0d, 0xd4, 0x36, 0x8f, 0x8e, 0x4e, 0x62, 0x66, 0xaa, 0x93, 0x77, 0x76, 0x22, 0xdb,
	0xd6, 0x8f, 0xec, 0x83, 0x7e, 0xdf, 0xd1, 0x70, 0xd3, 0x5e, 0xd2, 0x6f, 0xbb, 0x3d, 0x4a, 0xd7,
	0x3b, 0x5f, 0x15, 0x3f, 0xe5, 0xc3, 0x0f, 0x50, 0x81, 0xff, 0xfc, 0xfd, 0x23, 0x00, 0x00, 0xff,
	0xff, 0x1c, 0xad, 0xf3, 0xdc, 0x3a, 0x06, 0x00, 0x00,
}
