// Code generated by protoc-gen-go. DO NOT EDIT.
// source: configuration.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	configuration.proto
	environment.proto
	user.proto
	activity.proto
	soapbox.proto
	application.proto
	deployment.proto
	version.proto

It has these top-level messages:
	ListConfigurationRequest
	ListConfigurationResponse
	GetLatestConfigurationRequest
	Configuration
	ConfigVar
	CreateConfigurationRequest
	DeleteConfigurationRequest
	ListEnvironmentRequest
	ListEnvironmentResponse
	GetEnvironmentRequest
	Environment
	DestroyEnvironmentRequest
	User
	CreateUserRequest
	GetUserRequest
	LoginUserRequest
	LoginUserResponse
	ListActivitiesResponse
	Activity
	Empty
	Application
	ListApplicationRequest
	ListApplicationResponse
	GetApplicationRequest
	ApplicationMetric
	ApplicationMetricsResponse
	GetApplicationMetricsRequest
	ListDeploymentRequest
	ListDeploymentResponse
	GetDeploymentRequest
	GetLatestDeploymentRequest
	Deployment
	StartDeploymentResponse
	GetDeploymentStatusRequest
	GetDeploymentStatusResponse
	TeardownDeploymentRequest
	GetVersionResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ListConfigurationRequest struct {
	EnvironmentId int32 `protobuf:"varint,1,opt,name=environment_id,json=environmentId" json:"environment_id,omitempty"`
}

func (m *ListConfigurationRequest) Reset()                    { *m = ListConfigurationRequest{} }
func (m *ListConfigurationRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListConfigurationRequest) ProtoMessage()               {}
func (*ListConfigurationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ListConfigurationRequest) GetEnvironmentId() int32 {
	if m != nil {
		return m.EnvironmentId
	}
	return 0
}

type ListConfigurationResponse struct {
	Configs []*Configuration `protobuf:"bytes,1,rep,name=configs" json:"configs,omitempty"`
}

func (m *ListConfigurationResponse) Reset()                    { *m = ListConfigurationResponse{} }
func (m *ListConfigurationResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListConfigurationResponse) ProtoMessage()               {}
func (*ListConfigurationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListConfigurationResponse) GetConfigs() []*Configuration {
	if m != nil {
		return m.Configs
	}
	return nil
}

type GetLatestConfigurationRequest struct {
	EnvironmentId int32 `protobuf:"varint,1,opt,name=environment_id,json=environmentId" json:"environment_id,omitempty"`
}

func (m *GetLatestConfigurationRequest) Reset()                    { *m = GetLatestConfigurationRequest{} }
func (m *GetLatestConfigurationRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetLatestConfigurationRequest) ProtoMessage()               {}
func (*GetLatestConfigurationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetLatestConfigurationRequest) GetEnvironmentId() int32 {
	if m != nil {
		return m.EnvironmentId
	}
	return 0
}

type Configuration struct {
	EnvironmentId int32                      `protobuf:"varint,1,opt,name=environment_id,json=environmentId" json:"environment_id,omitempty"`
	Version       int32                      `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	CreatedAt     *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	ConfigVars    []*ConfigVar               `protobuf:"bytes,4,rep,name=config_vars,json=configVars" json:"config_vars,omitempty"`
}

func (m *Configuration) Reset()                    { *m = Configuration{} }
func (m *Configuration) String() string            { return proto1.CompactTextString(m) }
func (*Configuration) ProtoMessage()               {}
func (*Configuration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Configuration) GetEnvironmentId() int32 {
	if m != nil {
		return m.EnvironmentId
	}
	return 0
}

func (m *Configuration) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Configuration) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Configuration) GetConfigVars() []*ConfigVar {
	if m != nil {
		return m.ConfigVars
	}
	return nil
}

type ConfigVar struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *ConfigVar) Reset()                    { *m = ConfigVar{} }
func (m *ConfigVar) String() string            { return proto1.CompactTextString(m) }
func (*ConfigVar) ProtoMessage()               {}
func (*ConfigVar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ConfigVar) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigVar) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CreateConfigurationRequest struct {
	EnvironmentId int32        `protobuf:"varint,1,opt,name=environment_id,json=environmentId" json:"environment_id,omitempty"`
	ConfigVars    []*ConfigVar `protobuf:"bytes,2,rep,name=config_vars,json=configVars" json:"config_vars,omitempty"`
}

func (m *CreateConfigurationRequest) Reset()                    { *m = CreateConfigurationRequest{} }
func (m *CreateConfigurationRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateConfigurationRequest) ProtoMessage()               {}
func (*CreateConfigurationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateConfigurationRequest) GetEnvironmentId() int32 {
	if m != nil {
		return m.EnvironmentId
	}
	return 0
}

func (m *CreateConfigurationRequest) GetConfigVars() []*ConfigVar {
	if m != nil {
		return m.ConfigVars
	}
	return nil
}

type DeleteConfigurationRequest struct {
	EnvironmentId int32 `protobuf:"varint,1,opt,name=environment_id,json=environmentId" json:"environment_id,omitempty"`
	Version       int32 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *DeleteConfigurationRequest) Reset()                    { *m = DeleteConfigurationRequest{} }
func (m *DeleteConfigurationRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteConfigurationRequest) ProtoMessage()               {}
func (*DeleteConfigurationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteConfigurationRequest) GetEnvironmentId() int32 {
	if m != nil {
		return m.EnvironmentId
	}
	return 0
}

func (m *DeleteConfigurationRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto1.RegisterType((*ListConfigurationRequest)(nil), "soapbox.ListConfigurationRequest")
	proto1.RegisterType((*ListConfigurationResponse)(nil), "soapbox.ListConfigurationResponse")
	proto1.RegisterType((*GetLatestConfigurationRequest)(nil), "soapbox.GetLatestConfigurationRequest")
	proto1.RegisterType((*Configuration)(nil), "soapbox.Configuration")
	proto1.RegisterType((*ConfigVar)(nil), "soapbox.ConfigVar")
	proto1.RegisterType((*CreateConfigurationRequest)(nil), "soapbox.CreateConfigurationRequest")
	proto1.RegisterType((*DeleteConfigurationRequest)(nil), "soapbox.DeleteConfigurationRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Configurations service

type ConfigurationsClient interface {
	ListConfigurations(ctx context.Context, in *ListConfigurationRequest, opts ...grpc.CallOption) (*ListConfigurationResponse, error)
	GetLatestConfiguration(ctx context.Context, in *GetLatestConfigurationRequest, opts ...grpc.CallOption) (*Configuration, error)
	CreateConfiguration(ctx context.Context, in *CreateConfigurationRequest, opts ...grpc.CallOption) (*Configuration, error)
	DeleteConfiguration(ctx context.Context, in *DeleteConfigurationRequest, opts ...grpc.CallOption) (*Empty, error)
}

type configurationsClient struct {
	cc *grpc.ClientConn
}

func NewConfigurationsClient(cc *grpc.ClientConn) ConfigurationsClient {
	return &configurationsClient{cc}
}

func (c *configurationsClient) ListConfigurations(ctx context.Context, in *ListConfigurationRequest, opts ...grpc.CallOption) (*ListConfigurationResponse, error) {
	out := new(ListConfigurationResponse)
	err := grpc.Invoke(ctx, "/soapbox.Configurations/ListConfigurations", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationsClient) GetLatestConfiguration(ctx context.Context, in *GetLatestConfigurationRequest, opts ...grpc.CallOption) (*Configuration, error) {
	out := new(Configuration)
	err := grpc.Invoke(ctx, "/soapbox.Configurations/GetLatestConfiguration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationsClient) CreateConfiguration(ctx context.Context, in *CreateConfigurationRequest, opts ...grpc.CallOption) (*Configuration, error) {
	out := new(Configuration)
	err := grpc.Invoke(ctx, "/soapbox.Configurations/CreateConfiguration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationsClient) DeleteConfiguration(ctx context.Context, in *DeleteConfigurationRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/soapbox.Configurations/DeleteConfiguration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Configurations service

type ConfigurationsServer interface {
	ListConfigurations(context.Context, *ListConfigurationRequest) (*ListConfigurationResponse, error)
	GetLatestConfiguration(context.Context, *GetLatestConfigurationRequest) (*Configuration, error)
	CreateConfiguration(context.Context, *CreateConfigurationRequest) (*Configuration, error)
	DeleteConfiguration(context.Context, *DeleteConfigurationRequest) (*Empty, error)
}

func RegisterConfigurationsServer(s *grpc.Server, srv ConfigurationsServer) {
	s.RegisterService(&_Configurations_serviceDesc, srv)
}

func _Configurations_ListConfigurations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationsServer).ListConfigurations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Configurations/ListConfigurations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationsServer).ListConfigurations(ctx, req.(*ListConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configurations_GetLatestConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationsServer).GetLatestConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Configurations/GetLatestConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationsServer).GetLatestConfiguration(ctx, req.(*GetLatestConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configurations_CreateConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationsServer).CreateConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Configurations/CreateConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationsServer).CreateConfiguration(ctx, req.(*CreateConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configurations_DeleteConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationsServer).DeleteConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Configurations/DeleteConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationsServer).DeleteConfiguration(ctx, req.(*DeleteConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Configurations_serviceDesc = grpc.ServiceDesc{
	ServiceName: "soapbox.Configurations",
	HandlerType: (*ConfigurationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListConfigurations",
			Handler:    _Configurations_ListConfigurations_Handler,
		},
		{
			MethodName: "GetLatestConfiguration",
			Handler:    _Configurations_GetLatestConfiguration_Handler,
		},
		{
			MethodName: "CreateConfiguration",
			Handler:    _Configurations_CreateConfiguration_Handler,
		},
		{
			MethodName: "DeleteConfiguration",
			Handler:    _Configurations_DeleteConfiguration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configuration.proto",
}

func init() { proto1.RegisterFile("configuration.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xb5, 0x9c, 0xb8, 0x42, 0x63, 0xec, 0xc3, 0xb8, 0x04, 0x75, 0xa1, 0xd4, 0xdd, 0xd2, 0xe2,
	0x93, 0x52, 0x1c, 0x7a, 0xe8, 0x31, 0x4d, 0x3f, 0x28, 0xb8, 0x17, 0x11, 0x7a, 0x08, 0x04, 0xb3,
	0xb1, 0x27, 0x46, 0x60, 0xed, 0xaa, 0xda, 0x95, 0x48, 0xff, 0x5d, 0xff, 0x51, 0xff, 0x42, 0x61,
	0x37, 0x52, 0x6d, 0x47, 0x32, 0x06, 0x9f, 0x34, 0xb3, 0x3b, 0xef, 0xed, 0xd3, 0x9b, 0x07, 0xa3,
	0x85, 0x92, 0xf7, 0xc9, 0xaa, 0xc8, 0x85, 0x49, 0x94, 0x8c, 0xb2, 0x5c, 0x19, 0x85, 0xbe, 0x56,
	0x22, 0xbb, 0x53, 0x0f, 0x6c, 0xf0, 0x58, 0xb8, 0x73, 0xf6, 0x6a, 0xa5, 0xd4, 0x6a, 0x4d, 0xe7,
	0xb6, 0xbb, 0x2b, 0xee, 0xcf, 0x4d, 0x92, 0x92, 0x36, 0x22, 0xcd, 0xdc, 0x00, 0xbf, 0x84, 0x70,
	0x96, 0x68, 0x73, 0xb5, 0xc9, 0x19, 0xd3, 0xaf, 0x82, 0xb4, 0xc1, 0xb7, 0x30, 0x24, 0x59, 0x26,
	0xb9, 0x92, 0x29, 0x49, 0x33, 0x4f, 0x96, 0xa1, 0x37, 0xf6, 0x26, 0xbd, 0x78, 0xb0, 0x71, 0xfa,
	0x7d, 0xc9, 0x7f, 0xc0, 0x8b, 0x06, 0x0a, 0x9d, 0x29, 0xa9, 0x09, 0xdf, 0x83, 0xef, 0xf4, 0xea,
	0xd0, 0x1b, 0x9f, 0x4c, 0xfa, 0xd3, 0xb3, 0xa8, 0x52, 0xb8, 0x0d, 0xa8, 0xc6, 0xf8, 0x57, 0x78,
	0xf9, 0x8d, 0xcc, 0x4c, 0x18, 0x3a, 0x4e, 0xd6, 0x1f, 0x0f, 0x06, 0x5b, 0xf8, 0x03, 0x81, 0x18,
	0x82, 0x5f, 0x52, 0xae, 0x13, 0x25, 0xc3, 0xae, 0xbd, 0xaf, 0x5a, 0xfc, 0x08, 0xb0, 0xc8, 0x49,
	0x18, 0x5a, 0xce, 0x85, 0x09, 0x4f, 0xc6, 0xde, 0xa4, 0x3f, 0x65, 0x91, 0xb3, 0x38, 0xaa, 0x2c,
	0x8e, 0xae, 0x2b, 0x8b, 0xe3, 0xe0, 0x71, 0xfa, 0xd2, 0xe0, 0x05, 0xf4, 0xdd, 0x0f, 0xce, 0x4b,
	0x91, 0xeb, 0xf0, 0xd4, 0x7a, 0x81, 0x3b, 0x5e, 0xfc, 0x14, 0x79, 0x0c, 0x8b, 0xaa, 0xd4, 0xfc,
	0x03, 0x04, 0xf5, 0x05, 0x22, 0x9c, 0x4a, 0x91, 0x92, 0xd5, 0x1c, 0xc4, 0xb6, 0xc6, 0xe7, 0xd0,
	0x2b, 0xc5, 0xba, 0x20, 0x2b, 0x34, 0x88, 0x5d, 0xc3, 0x1f, 0x80, 0x5d, 0xd9, 0x87, 0x8f, 0xb0,
	0x6f, 0x57, 0x70, 0xf7, 0x20, 0xc1, 0xb7, 0xc0, 0x3e, 0xd3, 0x9a, 0x8e, 0x7b, 0xb9, 0xd5, 0xff,
	0xe9, 0xdf, 0x2e, 0x0c, 0xb7, 0x98, 0x35, 0xde, 0x02, 0x3e, 0x09, 0x9f, 0xc6, 0xd7, 0xb5, 0xce,
	0xb6, 0x70, 0x33, 0xbe, 0x6f, 0xc4, 0x85, 0x97, 0x77, 0xf0, 0x06, 0xce, 0x9a, 0xc3, 0x88, 0xef,
	0x6a, 0xfc, 0xde, 0xb4, 0xb2, 0x96, 0xbc, 0xf3, 0x0e, 0x5e, 0xc3, 0xa8, 0x61, 0x4d, 0xf8, 0xe6,
	0x3f, 0xa0, 0x75, 0x89, 0x7b, 0x58, 0x67, 0x30, 0x6a, 0x58, 0xc1, 0x06, 0x6b, 0xfb, 0x82, 0xd8,
	0xb0, 0x1e, 0xfa, 0x92, 0x66, 0xe6, 0x37, 0xef, 0x7c, 0xf2, 0x6f, 0x7a, 0x2e, 0xd7, 0xcf, 0xec,
	0xe7, 0xe2, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x33, 0x43, 0xbe, 0x4f, 0x7e, 0x04, 0x00, 0x00,
}
