// Code generated by protoc-gen-go. DO NOT EDIT.
// source: environment.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ListEnvironmentRequest struct {
	ApplicationId int32 `protobuf:"varint,1,opt,name=application_id,json=applicationId" json:"application_id,omitempty"`
}

func (m *ListEnvironmentRequest) Reset()                    { *m = ListEnvironmentRequest{} }
func (m *ListEnvironmentRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListEnvironmentRequest) ProtoMessage()               {}
func (*ListEnvironmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *ListEnvironmentRequest) GetApplicationId() int32 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

type ListEnvironmentResponse struct {
	Environments []*Environment `protobuf:"bytes,1,rep,name=environments" json:"environments,omitempty"`
}

func (m *ListEnvironmentResponse) Reset()                    { *m = ListEnvironmentResponse{} }
func (m *ListEnvironmentResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListEnvironmentResponse) ProtoMessage()               {}
func (*ListEnvironmentResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *ListEnvironmentResponse) GetEnvironments() []*Environment {
	if m != nil {
		return m.Environments
	}
	return nil
}

type GetEnvironmentRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetEnvironmentRequest) Reset()                    { *m = GetEnvironmentRequest{} }
func (m *GetEnvironmentRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetEnvironmentRequest) ProtoMessage()               {}
func (*GetEnvironmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *GetEnvironmentRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Environment struct {
	Id            int32                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ApplicationId int32                      `protobuf:"varint,2,opt,name=application_id,json=applicationId" json:"application_id,omitempty"`
	Name          string                     `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Slug          string                     `protobuf:"bytes,4,opt,name=slug" json:"slug,omitempty"`
	CreatedAt     *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *Environment) Reset()                    { *m = Environment{} }
func (m *Environment) String() string            { return proto1.CompactTextString(m) }
func (*Environment) ProtoMessage()               {}
func (*Environment) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *Environment) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Environment) GetApplicationId() int32 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *Environment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Environment) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Environment) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type DestroyEnvironmentRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DestroyEnvironmentRequest) Reset()                    { *m = DestroyEnvironmentRequest{} }
func (m *DestroyEnvironmentRequest) String() string            { return proto1.CompactTextString(m) }
func (*DestroyEnvironmentRequest) ProtoMessage()               {}
func (*DestroyEnvironmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *DestroyEnvironmentRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto1.RegisterType((*ListEnvironmentRequest)(nil), "soapbox.ListEnvironmentRequest")
	proto1.RegisterType((*ListEnvironmentResponse)(nil), "soapbox.ListEnvironmentResponse")
	proto1.RegisterType((*GetEnvironmentRequest)(nil), "soapbox.GetEnvironmentRequest")
	proto1.RegisterType((*Environment)(nil), "soapbox.Environment")
	proto1.RegisterType((*DestroyEnvironmentRequest)(nil), "soapbox.DestroyEnvironmentRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Environments service

type EnvironmentsClient interface {
	ListEnvironments(ctx context.Context, in *ListEnvironmentRequest, opts ...grpc.CallOption) (*ListEnvironmentResponse, error)
	GetEnvironment(ctx context.Context, in *GetEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error)
	CreateEnvironment(ctx context.Context, in *Environment, opts ...grpc.CallOption) (*Environment, error)
	DestroyEnvironment(ctx context.Context, in *DestroyEnvironmentRequest, opts ...grpc.CallOption) (*Empty, error)
}

type environmentsClient struct {
	cc *grpc.ClientConn
}

func NewEnvironmentsClient(cc *grpc.ClientConn) EnvironmentsClient {
	return &environmentsClient{cc}
}

func (c *environmentsClient) ListEnvironments(ctx context.Context, in *ListEnvironmentRequest, opts ...grpc.CallOption) (*ListEnvironmentResponse, error) {
	out := new(ListEnvironmentResponse)
	err := grpc.Invoke(ctx, "/soapbox.Environments/ListEnvironments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentsClient) GetEnvironment(ctx context.Context, in *GetEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error) {
	out := new(Environment)
	err := grpc.Invoke(ctx, "/soapbox.Environments/GetEnvironment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentsClient) CreateEnvironment(ctx context.Context, in *Environment, opts ...grpc.CallOption) (*Environment, error) {
	out := new(Environment)
	err := grpc.Invoke(ctx, "/soapbox.Environments/CreateEnvironment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentsClient) DestroyEnvironment(ctx context.Context, in *DestroyEnvironmentRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/soapbox.Environments/DestroyEnvironment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Environments service

type EnvironmentsServer interface {
	ListEnvironments(context.Context, *ListEnvironmentRequest) (*ListEnvironmentResponse, error)
	GetEnvironment(context.Context, *GetEnvironmentRequest) (*Environment, error)
	CreateEnvironment(context.Context, *Environment) (*Environment, error)
	DestroyEnvironment(context.Context, *DestroyEnvironmentRequest) (*Empty, error)
}

func RegisterEnvironmentsServer(s *grpc.Server, srv EnvironmentsServer) {
	s.RegisterService(&_Environments_serviceDesc, srv)
}

func _Environments_ListEnvironments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentsServer).ListEnvironments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Environments/ListEnvironments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentsServer).ListEnvironments(ctx, req.(*ListEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environments_GetEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentsServer).GetEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Environments/GetEnvironment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentsServer).GetEnvironment(ctx, req.(*GetEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environments_CreateEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Environment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentsServer).CreateEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Environments/CreateEnvironment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentsServer).CreateEnvironment(ctx, req.(*Environment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environments_DestroyEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentsServer).DestroyEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Environments/DestroyEnvironment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentsServer).DestroyEnvironment(ctx, req.(*DestroyEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Environments_serviceDesc = grpc.ServiceDesc{
	ServiceName: "soapbox.Environments",
	HandlerType: (*EnvironmentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEnvironments",
			Handler:    _Environments_ListEnvironments_Handler,
		},
		{
			MethodName: "GetEnvironment",
			Handler:    _Environments_GetEnvironment_Handler,
		},
		{
			MethodName: "CreateEnvironment",
			Handler:    _Environments_CreateEnvironment_Handler,
		},
		{
			MethodName: "DestroyEnvironment",
			Handler:    _Environments_DestroyEnvironment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "environment.proto",
}

func init() { proto1.RegisterFile("environment.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4d, 0x6b, 0xea, 0x40,
	0x18, 0x85, 0x4d, 0xfc, 0xc2, 0x57, 0x0d, 0xd7, 0xe1, 0xde, 0xdb, 0x34, 0x8b, 0x1a, 0x06, 0x4a,
	0x03, 0x85, 0x08, 0x76, 0xd3, 0xae, 0x8a, 0xfd, 0xa0, 0x1f, 0x74, 0x95, 0x16, 0x0a, 0xdd, 0x48,
	0x34, 0x63, 0x18, 0x30, 0x99, 0x69, 0x66, 0x2c, 0xf5, 0x17, 0xf5, 0x6f, 0xf4, 0xa7, 0x15, 0x13,
	0x8d, 0x51, 0x47, 0xba, 0xca, 0xcc, 0xc9, 0x99, 0xc3, 0xfb, 0x3e, 0x07, 0x3a, 0x24, 0xfe, 0xa0,
	0x09, 0x8b, 0x23, 0x12, 0x4b, 0x97, 0x27, 0x4c, 0x32, 0x54, 0x17, 0xcc, 0xe7, 0x23, 0xf6, 0x69,
	0xb5, 0xc6, 0x2c, 0x9e, 0xd0, 0x30, 0x93, 0xad, 0xf6, 0x52, 0x5e, 0x5e, 0xbb, 0x21, 0x63, 0xe1,
	0x94, 0xf4, 0xd2, 0xdb, 0x68, 0x36, 0xe9, 0x49, 0x1a, 0x11, 0x21, 0xfd, 0x88, 0x67, 0x06, 0x7c,
	0x09, 0xff, 0x9f, 0xa8, 0x90, 0xb7, 0xeb, 0x7c, 0x8f, 0xbc, 0xcf, 0x88, 0x90, 0xe8, 0x18, 0x0c,
	0x9f, 0xf3, 0x29, 0x1d, 0xfb, 0x92, 0xb2, 0x78, 0x48, 0x03, 0x53, 0xb3, 0x35, 0xa7, 0xea, 0xb5,
	0x0b, 0xea, 0x43, 0x80, 0x9f, 0xe1, 0x60, 0x27, 0x40, 0x70, 0x16, 0x0b, 0x82, 0xce, 0xa1, 0x55,
	0x98, 0x5b, 0x98, 0x9a, 0x5d, 0x76, 0x9a, 0xfd, 0xbf, 0xee, 0x6a, 0xc4, 0xe2, 0x9b, 0x0d, 0x27,
	0x3e, 0x81, 0x7f, 0x77, 0x44, 0x35, 0x94, 0x01, 0x7a, 0x3e, 0x88, 0x4e, 0x03, 0xfc, 0xa5, 0x41,
	0xb3, 0x60, 0xdb, 0xfe, 0xaf, 0x58, 0x42, 0x57, 0x2c, 0x81, 0x10, 0x54, 0x62, 0x3f, 0x22, 0x66,
	0xd9, 0xd6, 0x9c, 0x86, 0x97, 0x9e, 0x17, 0x9a, 0x98, 0xce, 0x42, 0xb3, 0x92, 0x69, 0x8b, 0x33,
	0xba, 0x00, 0x18, 0x27, 0xc4, 0x97, 0x24, 0x18, 0xfa, 0xd2, 0xac, 0xd9, 0x9a, 0xd3, 0xec, 0x5b,
	0x6e, 0xc6, 0xd8, 0x5d, 0x31, 0x76, 0x5f, 0x56, 0x8c, 0xbd, 0xc6, 0xd2, 0x3d, 0x90, 0xf8, 0x14,
	0x0e, 0x6f, 0x88, 0x90, 0x09, 0x9b, 0xff, 0xbe, 0x56, 0xff, 0x5b, 0x87, 0x56, 0xc1, 0x26, 0xd0,
	0x2b, 0xfc, 0xd9, 0xa2, 0x2c, 0x50, 0x37, 0x07, 0xa9, 0x6e, 0xd0, 0xb2, 0xf7, 0x1b, 0xb2, 0x86,
	0x70, 0x09, 0xdd, 0x83, 0xb1, 0x49, 0x1a, 0x1d, 0xe5, 0xaf, 0x94, 0x15, 0x58, 0xca, 0xfe, 0x70,
	0x09, 0x0d, 0xa0, 0x73, 0x9d, 0x6e, 0x5b, 0x0c, 0x53, 0x9a, 0xf7, 0x46, 0x3c, 0x02, 0xda, 0x65,
	0x84, 0x70, 0xee, 0xde, 0x0b, 0xd0, 0x32, 0xd6, 0x89, 0x11, 0x97, 0x73, 0x5c, 0xba, 0xaa, 0xbf,
	0x55, 0xb3, 0x42, 0x6a, 0xe9, 0xe7, 0xec, 0x27, 0x00, 0x00, 0xff, 0xff, 0x21, 0xcc, 0x30, 0xf0,
	0x44, 0x03, 0x00, 0x00,
}
