---
- hosts: all
  user: ec2-user
  become: True
  tasks:
    - name: copy runit rpm to target
      copy:
        src: files/runit-2.1.2-1.amzn1.x86_64.rpm
        dest: /tmp/runit.rpm

    - name: copy rsyslog repo file to target
      copy:
        src: files/rsyslog.repo
        dest: /etc/yum.repos.d/rsyslog.repo

    - name: install latest rsyslog
      yum:
        name: rsyslog
        state: latest
        disablerepo: amzn-main

    - name: install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - nginx
        - rsyslog-elasticsearch
        - /tmp/runit.rpm

    - name: start services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - docker
        - nginx
        - rsyslog

    - name: add ec2-user to docker group
      user:
        name: ec2-user
        append: yes
        groups: docker

    - name: install nginx configs
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      with_items:
        - src: files/app.conf
          dest: /etc/nginx/app.conf
        - src: files/init.conf
          dest: /etc/nginx/nginx.conf

    - name: Uncomment UDP server lines from /etc/rsyslog.conf
      lineinfile:
        dest: /etc/rsyslog.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - regexp: "^#$ModLoad"
          line: "$ModLoad imudp"
        - regexp: "^#$UDPServerRun"
          line: "$UDPServerRun 514"

    - name: install /etc/rsyslog.d/elasticsearch.conf
      copy:
        src: "files/elasticsearch.conf"
        dest: "/etc/rsyslog.d/elasticsearch.conf"

    - name: restart services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - nginx
        - rsyslog
